### ISSUE TITLE
[BUG][typescript-fetch] Set is not converted to Array when "typeMappings": {  "Set": "Array"} is provided

### ISSUE THREAD

**Issue by nikosanctioned** [OpenAPITools/openapi-generator#19874]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I have get the error TypeError names?.find is not a function at runtime
          
##### Steps to reproduce

Run generator => run the app part that relates to using uniqueItems: true names property

**Comment by verbetchii** [comment]
up!

I have the same issues after I upgraded the version from 6.6.0 to 7.12.0 (most likely, it's breaking changes from 7.x.x)
so is there any way to convert **Set** of strings coming from yaml with `uniqueItems: true` to strings[] with the flag -`-type-mappings=Set=array` as how it was in version 6.6.0?
it is very useful for some cases
