### ISSUE TITLE
[BUG][Go] Query parameter with oneOf enum doesn't work with defaultValue

### ISSUE THREAD

**Issue by AlanCitrix** [OpenAPITools/openapi-generator#16574]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using an enum schema with `oneOf` and `default`, the new default value handling from #15126 causes the generated code to not build.

##### openapi-generator version

master @ 8b15d482

##### OpenAPI declaration file content or url

```yaml
openapi: 3.1.0
servers:
  - url: 'http://petstore.swagger.io/v2'
info:
  description: >-
    This is a sample server Petstore server. For this sample, you can use the api key
    `special-key` to test the authorization filters.
  version: 1.0.0
  title: OpenAPI Petstore
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: pet
    description: Everything about your Pets
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
paths:
  /pet/findByStatus:
    get:
      tags:
        - pet
      summary: Finds Pets by status
      description: Find pets by a single status
      operationId: findPetsByStatus
      parameters:
        - name: status
          in: query
          description: Status value that needs to be considered for filter
          schema:
            default: "available"
            oneOf:
              - $ref: '#/components/schemas/StatusType'
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid status value
components:
  schemas:
    StatusType:
      schema:
        type: string
        enum:
          - available
          - pending
          - sold
    Pet:
      title: a Pet
      description: A pet for sale in the pet store
      type: object
      required:
        - name
        - photoUrls
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: doggie
        status:
          $ref: '#/components/schemas/StatusType'
      xml:
        name: Pet

```

##### Generation Details

```shell
> java -jar .\openapi-generator-cli.jar generate -g go -o petstore -i petstore.yaml  --package-name petstore -t C:\repos\openapi-generator\modules\openapi-generator\src\main\resources\go
```

Generates the following invalid go:
```go
	if r.status != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "status", r.status, "")
	} else {
		var defaultValue interface{} = available
		r.status = &defaultValue
	}
```

```shell
> go build
.\api_pet.go:80:34: undefined: available
```

##### Steps to reproduce

A query parameter using a schema with `default` and `oneOf`:
```yaml
      parameters:
        - name: status
          in: query
          description: Status value that needs to be considered for filter
          schema:
            default: "available"
            oneOf:
              - $ref: '#/components/schemas/StatusType'
```

##### Related issues/PRs

Issue introduced by #15126 

##### Suggest a fix

I tried running the generation with `defaultValue=false` but the didn't stop the default value code from being generated:
```
java -jar .\openapi-generator-cli.jar generate -g go -o petstore-i petstore.yaml  --additional-properties="defaultValue=false" --package-name petstore -t C:\repos\openapi-generator\modules\openapi-generator\src\main\resources\go
```

**Comment by wing328** [comment]
```
          schema:
            default: "available"
            oneOf:
              - $ref: '#/components/schemas/StatusType'
```

If you change oneOf to allOf, would that work?

**Comment by AlanCitrix** [comment]
Unfortunately that produces the same result.

**Comment by AlanCitrix** [comment]
Actually my mistake, `allOf` did do the trick. There was another bug in the swagger which I've fixed in the description. Thanks for the workaround.
