### ISSUE TITLE
[BUG] [Spring] Nullable annotation not imported in Spring-Boot controllers

### ISSUE THREAD

**Issue by jpfinne** [OpenAPITools/openapi-generator#23581]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Compilation error for generated spring-boot generated rest controller.
`@Nullable` annotation is set for NativeWebRequest.  The annotation is not imported in all cases.  For example when the operations have only required arguments.

##### openapi-generator version

7.22.0-SNAPSHOT

##### Generation Details

java  -jar openapi-generator-cli.jar  generate -g spring --library spring-boot -i modules/openapi-generator/src/test/resources/3_0/petstore.yaml -o /tmp/output

##### Steps to reproduce

The generated `/tmp/output/src/main/java/org/openapitools/api/UserApiController.java`
contains a `@Nullable` annotation, but no import.

It gives a compilation error

##### Related issues/PRs

Regression due to #23256

##### Suggest a fix

Quick fix: remove the annotation from `apiController.mustache`
Mid term fix:
  
  correclty add `@Nullable` annotation in all the java and spring generators.  The goal is is to avoid false alarms when using JSpecify. Ensure that `@Nullable` annotations are correctly imported
