### ISSUE TITLE
[BUG] typescript-fetch 6.0.1 template compile issues

### ISSUE THREAD

**Issue by organom** [OpenAPITools/openapi-generator#13343]
# 🐛 Bug Report:

### Describe the bug
When using latest typescript template with react app, the latest typescript template (6.0.1) has typescript issues, while 6.0.0 was ok.

### Steps to Reproduce

1. create `test` folder with the following files inside:
`package.json`
``` json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.ts",
  "scripts": {
    "build": "./node_modules/typescript/bin/tsc",
    "generate:sdk": "./node_modules/.bin/openapi-generator-cli version-manager set 6.0.1 && ./node_modules/.bin/openapi-generator-cli generate -i openapi.yaml --additional-properties=modelPropertyNaming=original,paramNaming=original,enumPropertyNaming=original -g typescript-fetch"
  },
  "dependencies": {
    "@openapitools/openapi-generator-cli": "^2.5.1",
    "typescript": "^4.7.2"
  },
  "author": "",
  "license": "ISC"
}
```

`tsconfig.json`
``` json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "exclude": ["node_modules", "**/*.test.ts"]
}
```

`openapi.yaml`
``` yaml
openapi: 3.0.1
info:
  title: Test
  description: Test
  version: "0.1"

tags:
  - name: Test
    description: test

security:
  - BearerToken: [ ]

paths:
  /test:
    get:
      operationId: get_test
      tags:
        - Test
      description: Retrieves a test
      responses:
        '200':
          description: Operation has completed successfully
```

2. cd into `test` folder and run `npm install`
3. run `npm run generate:sdk && npm run build` and confirm that errors are displayed

``` bash
> test@1.0.0 build
> ./node_modules/typescript/bin/tsc

runtime.ts:119:13 - error TS2532: Object is possibly 'undefined'.

119         if (response.status >= 200 && response.status < 300) {
                ~~~~~~~~

runtime.ts:119:39 - error TS2532: Object is possibly 'undefined'.

119         if (response.status >= 200 && response.status < 300) {
                                          ~~~~~~~~

runtime.ts:120:13 - error TS2322: Type 'Response | undefined' is not assignable to type 'Response'.
  Type 'undefined' is not assignable to type 'Response'.

120             return response;
                ~~~~~~~~~~~~~~~~

runtime.ts:122:33 - error TS2345: Argument of type 'Response | undefined' is not assignable to parameter of type 'Response'.
  Type 'undefined' is not assignable to type 'Response'.

122         throw new ResponseError(response, 'Response returned an error code');
                                    ~~~~~~~~

runtime.ts:205:31 - error TS2532: Object is possibly 'undefined'.

205                     response: response.clone(),
                                  ~~~~~~~~

runtime.ts:239:14 - error TS2415: Class 'FetchError' incorrectly extends base class 'Error'.
  Types of property 'cause' are incompatible.
    Type 'unknown' is not assignable to type 'Error | undefined'.

239 export class FetchError extends Error {
                 ~~~~~~~~~~


Found 6 errors in the same file, starting at: runtime.ts:119
```

4. open `package.json` and change `6.0.1` to `6.0.0` in `generate:sdk` command
5. run again `npm run generate:sdk && npm run build` and confirm **no** errors are displayed

### Expected behavior
Should work like with version 6.0.0

### Package System (please complete the following information):
 - @openapitools/openapi-generator-cli 2.5.1
 - typescript 4.7.2
 - nodejs 16.15.1
 - npm 8.13.2

**Comment by vaban-ru** [comment]
I have same problem, any news about this?

**Comment by mpatelpa** [comment]
I m running into the same error reported by [organom](https://github.com/organom) when upgrading from 6.0.0 to 6.0.1.  
The templating fix has been merged to the master branch https://github.com/OpenAPITools/openapi-generator/commit/97daba5c.  Can this change be patched in 6.0 patch release?

**Comment by ardc-shorn** [comment]
I was using openapi-generator 6.0.0 because of this issue.

Today, my github CI build was failing because:
> Could not GET 'https://jcenter.bintray.com/com/fasterxml/jackson/datatype/jackson-datatype-guava/2.13.1/jackson-datatype-guava-2.13.1.jar'

I updated to 6.2.0 and my build issue went away and my Typescript code still compiles, so I think this is is resolved... somehow?

**Comment by organom** [comment]
@ardc-shorn thanks for the heads up, yes it appears to be solved, tested with: 6.2.0 and 6.2.1 

Closing the issue :)
