### PR TITLE
fix(#2018): add PATCH import

### PR DESCRIPTION
**Pull request by tnmtechnologies**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

fix issue #2018  
- Add explicit PATCH import into JavaJaxRS/resteasy/api.mustache file
- Update jaxrs-resteasy samples

### CODE REVIEW

**Comment by wing328** [comment]
@tnmtechnologies thanks for the PR. When you've time in the coming week, can you please ping me vai Gitter.im or Google Hangout to have a quick chat on this PR?

**Comment by tnmtechnologies** [comment]
Hello William,


Thank you for the merge.

No problem, I will ping you in the coming week.

For your knowledge, I also submitted this PR https://github.com/OpenAPITools/openapi-generator/pull/2039 <https://github.com/OpenAPITools/openapi-generator/pull/2039>.
Last week, I submitted this issue  https://github.com/OpenAPITools/openapi-generator/issues/2089 <https://github.com/OpenAPITools/openapi-generator/issues/2089>. 
Sorry, I didn’t understand why it no more works in 3.3.4. Unfortunately I was not able to test it with 4.0.0-SNAPSHOT-beta2.
When I run the jaxrs-resteasy generator on the same yaml files, a NullPointerException is thrown. 


KR,


Michel

**Comment by jmini** [comment]
The result of the PR is that we have following imports:

```java
import io.swagger.jaxrs.*;
import io.swagger.jaxrs.PATCH;

import javax.ws.rs.*;
```

I didn't know that this is allowed.

I think I would prefer a solution where we remove the 2 lines `import io.swagger.jaxrs...;` and use the fully qualified name of the annotation like `@io.swagger.jaxrs.PATCH` in the generated code.

What do you think?

**Comment by tnmtechnologies** [comment]
@jmini I agree, it would be better to just import what we need.
But I think there is a problem in the PR. The fully qualified annotation io.swagger.jaxrs.PATCH allows the build to succeed as it fixes a compilation error. But at runtime, I think it would fail because this annotation is not a JAXRS one. 
The JAXRS fully qualified annotation should be javax.ws.rs.PATCH only available from JAXRS 2.1. I have tested it with thorntail 2.4.0 (JAXRS 2.1 compliant) and it works well.

Does anyone have an example of working PATCH example with JAXRS version 2.0 or earlier knowing that PATCH is not supported?

My proposal is to use the fully qualified annotation javax.ws.rs.PATCH knowing that it only works with JAXRS 2.1.
@jmini @wing328 please what is your point of view?

**Comment by wing328** [comment]
> My proposal is to use the fully qualified annotation javax.ws.rs.PATCH knowing that it only works with JAXRS 2.1.


My take is to go with your proposed solution. If later there are valid use cases to use " io.swagger.jaxrs.PATCH", we may consider adding an option to allow users to choose between the two.

**Comment by wing328** [comment]
@tnmtechnologies closing this as there's no update. Feel free to reopen or submit a new one when it's ready for review.
