### PR TITLE
fix(go): avoid duplicate unknown enum defaults

### LINKED ISSUE #23844: [BUG][Go] enumUnknownDefaultCase generates colliding UNKNOWN_DEFAULT_OPEN_API constants when enumClassPrefix=false
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

When using `enumUnknownDefaultCase=true` with the Go generator and `enumClassPrefix=false` (the default), every generated enum type emits a bare `UNKNOWN_DEFAULT_OPEN_API` constant. Since all enum models live in the same Go package, this causes a compilation error:

```
UNKNOWN_DEFAULT_OPEN_API redeclared in this block
        model_status_a.go:XX: other declaration of UNKNOWN_DEFAULT_OPEN_API
```

The sentinel constant is added as an `enumVar` and rendered through the same template path as regular constants:

```mustache
{{#enumClassPrefix}}{{{classname.toUpperCase}}}_{{/enumClassPrefix}}{{name}}
```

When `enumClassPrefix=false`, no prefix is applied, so every enum gets an identical `UNKNOWN_DEFAULT_OPEN_API` constant.

Setting `enumClassPrefix=true` fixes the collision but renames **all** existing enum constants (e.g. `ProvisionHalted` becomes `MODELPROVISIONSTAGEVALUE_ProvisionHalted`), which is a breaking change for consumers.

##### openapi-generator version

7.22.0 (not a regression — this is the first release with Go support for `enumUnknownDefaultCase`, introduced by PR #23417)

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  version: 1.0.0
  title: Test API
paths: {}
components:
  schemas:
    StatusA:
      type: string
      enum:
        - active
        - inactive
    StatusB:
      type: string
      enum:
        - pending
        - completed
```

##### Generation Details

```bash
openapi-generator-cli generate \
  -i spec.yaml \
  -g go \
  --additional-properties enumUnknownDefaultCase=true \
  --package-name myapi
```

##### Steps to reproduce

1. Generate a Go client with the above spec and `enumUnknownDefaultCase=true` (without `enumClassPrefix=true`)
2. Attempt to compile the generated code: `go build ./...`
3. Observe: `UNKNOWN_DEFAULT_OPEN_API redeclared in this block`

##### Related issues/PRs

- PR #23417 introduced `enumUnknownDefaultCase` for Go
- Issue #18747 tracked the original missing feature

##### Suggest a fix

The sentinel constant should be unique per enum type when `enumClassPrefix=false`. The template could unconditionally prefix the sentinel with the classname, e.g.:

```mustache
{{{classname}}}UnknownDefaultOpenApi {{{classname}}} = "unknown_default_open_api"
```

This would generate `StatusAUnknownDefaultOpenApi`, `StatusBUnknownDefaultOpenApi`, etc. — unique names without requiring `enumClassPrefix=true` and without renaming existing constants.

### PR DESCRIPTION
**Pull request by SJvaca30**
Fixes #23844.

### What
- Adds a model-specific prefix to the synthetic Go `unknown_default_open_api` enum fallback when `enumClassPrefix=false`.
- Leaves user-defined enum constants unprefixed.
- Adds regression coverage with two enum models generated into the same Go package.

### Testing
- `./mvnw -pl modules/openapi-generator -am -Dtest=org.openapitools.codegen.go.GoClientCodegenTest#testEnumUnknownDefaultCaseUsesModelSpecificNamesWhenEnumClassPrefixDisabled -Dsurefire.failIfNoSpecifiedTests=false test`
- `./mvnw -pl modules/openapi-generator -am -Dtest=org.openapitools.codegen.go.GoClientCodegenTest -Dsurefire.failIfNoSpecifiedTests=false test`
- `git diff --check`

---
## Summary by cubic
Avoids duplicate Go enum fallback constants by prefixing the synthetic unknown default with the model name when `enumClassPrefix=false`. Fixes #23844.

- **Bug Fixes**
  - Prefixes the `unknown_default_open_api` fallback with the model name when `enumUnknownDefaultCase=true` and `enumClassPrefix=false`, preventing collisions across models in the same package.
  - Leaves user-defined enum constants unchanged.
  - Adds regression test with two enum models to verify unique names (e.g., STATUSA_UNKNOWN_DEFAULT_OPEN_API, STATUSB_UNKNOWN_DEFAULT_OPEN_API).
  - Documents the prefixing behavior in the Go generator docs.

<sup>Written for commit e2306993fab4dda0ef0f181d2ae59de2514f210e. Summary will update on new commits.</sup>

<a href="https://cubic.dev/pr/OpenAPITools/openapi-generator/pull/23909?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java [hunk 1]
```diff
@@ -576,6 +577,29 @@ public ModelsMap postProcessModels(ModelsMap objs) {
         return objs;
     }
 
+    @SuppressWarnings("unchecked")
+    private void prefixEnumUnknownDefaultCase(CodegenModel model) {
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java:588]: please add a docstring explaining what this function does

a few inline comments explaining the if blocks below would be helpful too

Comment (SJvaca30) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java:588]: Added Javadoc for `prefixEnumUnknownDefaultCase` and inline comments for the guard conditions and fallback-name update.

**Comment by wing328** [comment]
tested locally and the result is good (no compilation error)

```diff
--- a/model_status_a.go
+++ b/model_status_a.go
@@ -22,7 +22,7 @@ type StatusA string
 const (
        ACTIVE StatusA = "active"
        INACTIVE StatusA = "inactive"
-       UNKNOWN_DEFAULT_OPEN_API StatusA = "unknown_default_open_api"
+       STATUSA_UNKNOWN_DEFAULT_OPEN_API StatusA = "unknown_default_open_api"
 )

 // All allowed values of StatusA enum
@@ -46,7 +46,7 @@ func (v *StatusA) UnmarshalJSON(src []byte) error {
                }
        }

-       *v = UNKNOWN_DEFAULT_OPEN_API
+       *v = STATUSA_UNKNOWN_DEFAULT_OPEN_API
        return nil
 }

```

will merge once all the tests pass

**Comment by wing328** [comment]
cc @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04) @lwj5 (2023/04)

**Comment by wing328** [comment]
Thanks for the PR which has been merged.
