### ISSUE TITLE
[BUG] Java generator does not generate oneOf interface

### ISSUE THREAD

**Issue by Daemorinumi** [OpenAPITools/openapi-generator#11715]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

the java generator on openapi-generator-maven-plugin 5.4.0 doesn't compile with an openapi which contain an **oneOf** instructions.
The interfaces **OneOf** are not generated.

```
Compilation failure: Compilation failure:
[ERROR] /Users/XXX/git/service/contract/target/generated-sources/openapi/src/main/java/blabla/model/Person.java:[48,23] error: cannot find symbol
[ERROR]   symbol:   class OneOfCatDog
[ERROR]   location: class Person
```

I tried with previous versions and the only one which compile is the 4.3.1. 
Unfortunately the generated interface contain an empty **JsonSubTypes** annotation : the mapper cannot map correctly the object

```
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-25T12:39:36.701392+01:00[Europe/Paris]")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "pet_type", visible = true)
@JsonSubTypes({
})

public interface PersonPetOneOf  {
    public String getPetType();
}
```

##### openapi-generator version

version : 5.4.0

##### OpenAPI declaration file content or url

```
openapi: "3.0.3"
info:
  title: "notification"
  version: "1.0"
tags:
  - name: notify
servers:
  - url: /person
paths:
  /person:
    post:
      security:
        - basicAuth: []  
      tags:
        - notify
      operationId: aaa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '200':
          description : "retour ok"
         
components:
  securitySchemes:
    basicAuth:    
      type: http
      scheme: basic
  schemas:
    Pet:
      type: object
      required:
        - pet_type
      properties:
        pet_type:
          type: string
      discriminator:
        propertyName: pet_type
    Dog:    
      allOf:  
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            bark:
              type: boolean
            breed:
              type: string
              enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:     
      allOf: 
        - $ref: '#/components/schemas/Pet'
        - type: object
          # all other properties specific to a `Cat`
          properties:
            hunts:
              type: boolean
            age:
              type: integer
    Person:
      properties:
        name:
          type : string
        pet:
          oneOf:
             - $ref: '#/components/schemas/Cat'
             - $ref: '#/components/schemas/Dog'
          discriminator:
            propertyName: pet_type
```

##### Generation Details

java : version 11
maven : version 3.5.3
pom.xml
```
<plugin>
	<groupId>org.openapitools</groupId>
	<artifactId>openapi-generator-maven-plugin</artifactId>
	<version>5.4.0</version>
	<!-- <version>4.3.1</version> -->
	<executions>
		<execution>
			<goals>
				<goal>generate</goal>
			</goals>
			<configuration>
				<inputSpec>${project.basedir}/src/main/resources/static/openapi/notifier-v1.yaml</inputSpec>
				<generatorName>java</generatorName>
				<apiPackage>blabla.api</apiPackage>
				<modelPackage>blabla.model</modelPackage>
				<library>resttemplate</library>
				<configOptions>
					<generateModels>true</generateModels>
					<dateLibrary>java8</dateLibrary>
				</configOptions>
			</configuration>
		</execution>
	</executions>
</plugin>
```

##### Steps to reproduce

mvn clean install

##### Suggest a fix
The java generator should generate the OneOf Interface and the **JsonSubTypes** annotation should contains the object mapping.

**Comment by KirillKurdyukov** [comment]
+

**Comment by jeffrey-chu-mox** [comment]
Same issue

**Comment by mutyasaisrikar** [comment]
same issue. compilation error for class `OneOfAnyTypeAnyType`, even though that is not used in the class

**Comment by miguelk5** [comment]
same issue, any news ?

**Comment by Ravirael** [comment]
Same issue on version 6.2.1 with rest-assured library. Does work correctly on 4.3.1, so huge downgrade is an option for anyone needing this.

**Comment by rgaume-delfingen** [comment]
I am experiencing the same issue. I will try to use the 4.3.1 version.

**Comment by rgaume-delfingen** [comment]
On my side I cannot go back to 4.3.1 version since there is a null value into the oneOf possibilities it gives me a NPE a fix is to stay in the last version and extend the badly generated class to add the missing fields ;)

**Comment by sofiedc** [comment]
We use a patched version of openapi-generator for now where option useOneOfInterfaces is explicitely set to true.

We still ran into an issue though: method

public String toUrlQueryString(String prefix);

was not added to oneOf interfaces, leading to compile errors. So we post-process the generated sources now to add this method.
