### ISSUE TITLE
[BUG] 6.2.1 regression - JavaSpring `@NotNull` code annotation with no import

### ISSUE THREAD

**Issue by ardc-shorn** [OpenAPITools/openapi-generator#14059]
#### Bug Report Checklist

- [Yes] Have you provided a full/minimal spec to reproduce the issue?
- [No] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [No] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [Yes] Have you searched for related issues/PRs?
- [Yes] What's the actual output vs expected output?

##### Description

JavaSpring generator creates java files with `@NotNull` but there's no import for that symbol, resulting in javac error `cannot find symbol`.

##### openapi-generator version

`6.2.1`

This is a regression, was working on 6.2.0.

##### OpenAPI declaration file content or url

```yaml
    AuthzRequestStatus:
      type: string
      enum: ['APPROVED', 'REQUESTED', 'REJECTED']
```

Full file: https://github.com/au-research/raido-v2/blob/895de24f6dc9ec3a360ba04acf0f3ee1355b6d59/api-svc/idl-raid-v2/src/admin-experimental.yaml#L334

##### Generation Details

Project uses the Gradle plugin to generate, full configuration is here:
https://github.com/au-research/raido-v2/blob/895de24f6dc9ec3a360ba04acf0f3ee1355b6d59/api-svc/idl-raid-v2/build.gradle#L136

I think the relevant configuration item might be: `openApiNullable: "false"` and `useBeanValidation: "false"`?

##### Steps to reproduce

* run the standard Gradle `openApiGenerate` task
* then compile the generated code
* `javac` fails with error `cannot find symbol`

##### Suggest a fix

If `openApiNullable` and `useBeanValidation` set to false - `6.2.1` should not generate the `@NotNull` annotation.  `6.2.0` does not generate the annotation.

Possible workaround may be to find the template that generates the `@NotNull` and delete it.  Haven't dont it yet though.

**Comment by ardc-shorn** [comment]
Commit that introduced the issue:
https://github.com/OpenAPITools/openapi-generator/commit/0060dfd1#diff-d34f77bd237cdd0449fb17e44bf5485ecac1a2fa5b5a329943ac128bb12fb222
