### PR TITLE
[#4650] Fix StackOverflowError for recursive composite schemas

### LINKED ISSUE #4650: [BUG] StackOverflowError in DefaultCodegen.addProperties when a schemas with same name are referenced directly and indirectly
#### Bug Report Checklist

- [Y ] Have you provided a full/minimal spec to reproduce the issue?
- [ Y] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?  4.2.1
- [Y ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
java.lang.StackOverflowError, expected Sring generated project
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When trying to generate spring project from a complex .yaml file setup a java.lang.StackOverflowError is thrown.

The setup is the following:

Base.yaml contains a definition of Test
Blue.yaml contains a definition of Test which inherits with Allof from Base.yaml->Test
Green.yaml also contains a definition of Test which inherits  with Allof from Base.yaml->Test and also it has a reference to  Blue.yaml->Test

When generation is started for Green.yaml , DefaultCodegen.addProperties causes stack overflow.

Generator first loads the Base.yaml->Test reference in its cache.
The problem happens when the generator starts processing the Blue.yaml->Test reference in Green.yaml. 
It loads the Blue.yaml->Test but wrongly overrides the Base.yaml->Test  in its cache.
Blue.yaml->Test  is inheriting from Base.yaml->Test  but now after the override Blue.yaml->Test  inherits from itself and becomes corrupt!!!!!!!!!.
After this when DefaultCodegen.addProperties starts its work it goes into endless recursion trying to process the corrupted self referencing Blue.yaml->Test .

See the stack trace below:

[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: spring (server)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'spring' is considered stable.
[main] INFO  o.o.codegen.languages.SpringCodegen - ----------------------------------
[main] INFO  o.o.c.languages.AbstractJavaCodegen - Environment variable JAVA_POST_PROCESS_FILE not defined so the Java code may not be properly formatted. To define it, try 'export JAVA_POST_PROCESS_FILE="/usr/local/bin/clang-format -i"' (Linux/Mac)
[main] INFO  o.o.c.languages.AbstractJavaCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.c.languages.AbstractJavaCodegen - Processing operation test
[main] INFO  o.o.c.languages.AbstractJavaCodegen - Processing operation inbox_storeTaskResponse
Exception in thread "main" java.lang.StackOverflowError
        at org.apache.commons.lang3.StringUtils.isNotBlank(StringUtils.java:327)
        at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:2020)
        at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:2002)
        at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:2022)
        at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:2002)
        at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:2022)
        at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:2002)
        at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:2022)
        at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:2002)
        at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:2022)
        at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:2002)
##### openapi-generator version

4.2.1

##### Command line used for generation

openapi-generator generate -i task-test.yaml -g spring -o test

##### Suggest a fix

The problem seem to be that when loading a second ref .yaml file which contains schemas with the same name as a component from the other first ref.yaml file. The second component overrides the first component.

### PR DESCRIPTION
**Pull request by kthoms**
The generator ran into a loop when a composite schema recursively added itself. This change provides a reproducing example and fixes the issue by extending DefaultCodegen#addProperties() by an additional circuit breaker parameter.

When additionalProperties() is called with a schema instance for which the properties have already been added, the method directly returns and does not run into the loop.

To fix #4650

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java [hunk 1]
```diff
@@ -3264,13 +3264,16 @@ protected void addAdditionPropertiesToCodeGenModel(CodegenModel codegenModel, Sc
      * @param required   required property only
      * @param schema     schema in which the properties will be added to the lists
      */
-    protected void addProperties(Map<String, Schema> properties, List<String> required, Schema schema) {
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java:3267]: @kthoms thanks for the PR. Please update the docstring of the method as well since it's causing issues to the build: https://github.com/OpenAPITools/openapi-generator/runs/5213864795?check_suite_focus=true

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java (hunk 1 above)
Comment (kthoms) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java:3267]: I have updated the code and rebased it. The build fails in the samples. I don't think that it is related, WDYT?

**Comment by wing328** [comment]
Samples not up-to-date: https://github.com/OpenAPITools/openapi-generator/runs/5245407913?check_suite_focus=true

Can you please follow step 3 in the PR checklist to update the samples so that the CI can verify the result?

**Comment by kthoms** [comment]
Thanks for the pointer. Will do.

File: samples/openapi3/client/petstore/python/docs/Fruit.md [hunk 2]
```diff
@@ -5,10 +5,10 @@ a schema that tests oneOf and includes a schema level property
 ## Properties
 Name | Type | Description | Notes
 ------------ | ------------- | ------------- | -------------
-**cultivar** | **str** |  | 
-**length_cm** | **float** |  | 
 **color** | **str** |  | [optional] 
 **origin** | **str** |  | [optional] 
+**cultivar** | **str** |  | [optional] 
+**length_cm** | **float** |  | [optional]
```
[the remark this answers is not in the document]
Comment (kthoms) [reply samples/openapi3/client/petstore/python/docs/Fruit.md:11]: No, this looks like an unwanted side effect. Thanks for pointing this out! 
When I see this correctly the originating spec is
```modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml```
There these both properties are declared as required.
I need to have a look.

[the remark this answers is not in the document]
Comment (kthoms) [reply samples/openapi3/client/petstore/python/docs/Fruit.md]: Updated the code. Now the samples are untouched.

**Comment by kthoms** [comment]
Build fails here:
```
ok  	github.com/OpenAPITools/openapi-generator/samples/openapi3/client/petstore/go	28.525s
go: downloading github.com/gorilla/mux v1.7.3
?   	github.com/GIT_USER_ID/GIT_REPO_ID	[no test files]
# golang.org/x/net/http2
/home/circleci/.go_workspace/src/golang.org/x/net/http2/transport.go:417:45: undefined: os.ErrDeadlineExceeded
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (go-get) on project GoGinServer: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
```
This is also reported here: https://github.com/odeke-em/drive/issues/1128
So I assume the build failure is unrelated to the change.

**Comment by kthoms** [comment]
The Go upgrade resolved the previous issue, but now it fails with
```
store_api_test.go:31: Error while placing order: parsing time "\"2022-02-19T09:11:15.907+0000\"" as "\"2006-01-02T15:04:05Z07:00\"": cannot parse "+0000\"" as "Z07:00"
```

This issue I have found here:
https://github.com/OpenAPITools/openapi-generator/issues/1292

**Comment by wing328** [comment]
Please revert e881b193682a71243297d35e295d0e7db81fd19e and I'll fix it in the master.

**Comment by kthoms** [comment]
@wing328 Thanks for your patience. I've reverted the last commit.

**Comment by wing328** [comment]
Tested locally to confirm the fix
