### ISSUE TITLE
[BUG][JAVA][Spring] Config options for Pageable & ApiIgnore

### ISSUE THREAD

**Issue by morphlne** [OpenAPITools/openapi-generator#8360]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Trying to generate pure interfaces using next config:

```xml
<generateSupportingFiles>false</generateSupportingFiles>
<configOptions>
    <openApiNullable>false</openApiNullable>
    <java8>false</java8>
    <interfaceOnly>true</interfaceOnly>
    <hideGenerationTimestamp>true</hideGenerationTimestamp>
</configOptions>
```

Following lines are added to generated api file:
```java
import org.springframework.data.domain.Pageable;
import springfox.documentation.annotations.ApiIgnore;
```
and produced compilation error due those classes needed additional dependencies (spring-data-commons&springfox-core)

Didn't manage to find any option to disable those imports (like `openApiNullable` for disabling `org.openapitools.jackson.nullable.JsonNullable`)

##### openapi-generator version

5.0.0

##### OpenAPI declaration file content or url

Sample project for quick reproducing https://github.com/morphlne/openapi-generator-demo

##### Steps to reproduce
Clone https://github.com/morphlne/openapi-generator-demo.git
run `mvn compile`

##### Related issues/PRs

Both imports added in mustache files in PR: https://github.com/OpenAPITools/openapi-generator/pull/5022

##### Suggest a fix

Add support for next config options:
```xml
<usePageable>false</usePageable>
<useApiIgnore>false</useApiIgnore>
```

**Comment by feliperuiz** [comment]
I believe #8192 also relates to this. It seems to have been introduced by #5022, which added the imports for `@ApiIgnore` and `Pageable` without checking they are indeed required to be present.

[There seems to exist a computed flag/setting for the use of `@ApiIgnore`](https://github.com/OpenAPITools/openapi-generator/blob/ce893a84ff21f6719ecad01fb9e7b1e09346bffb/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java#L455-L457)—springfox as a whole, more accurately—but it [gets imported without checking it](https://github.com/OpenAPITools/openapi-generator/blob/ce893a84ff21f6719ecad01fb9e7b1e09346bffb/modules/openapi-generator/src/main/resources/JavaSpring/api.mustache#L37).

I was actually facing the same issue and was planning on coming up with a patch to only add those imports when they're needed, but I couldn't find my way around the test suite—which test methods/resources would need to be updated, or even how to properly run the tests in the first place =/

**Comment by borsch** [comment]
@feliperuiz there is no need to run tests. after you fix templates you simply has to re-generate all related samples via `./bin/generate-samples.sh` to generate all or `./bin/generate-samples.sh bin/configs/CONFIG.yaml`  to generate specific (ex: `./bin/generate-samples.sh bin/configs/java-vertex.yaml`

**Comment by morphlne** [comment]
Fixed locally by adding new config options & changing mustache template. Will prepare PR for this fix

**Comment by MatCyg** [comment]
Is there any workaround available already? (beside adding unnecessary imports to you project)

**Comment by morphlne** [comment]
@MatCyg As quick solution you can use 5.0.0-beta2 and any earlier version

**Comment by pierrefevrier** [comment]
Same problem with version 5.0.1

**Comment by bruteforce** [comment]
Any workaround?

**Comment by morphlne** [comment]
Resolved in 5.3.0
