### ISSUE TITLE
[BUG][typescript-fetch]  error TS2532: Object is possibly 'undefined' for optional model properties

### ISSUE THREAD

**Issue by kota65535** [OpenAPITools/openapi-generator#17970]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Given OpenAPI schema definition:

```yaml
title: Task
description: Task
type: object
properties:
  id:
    type: integer
    readOnly: true
  title:
    type: string
  dueDate:
    type: string
    format: date
required:
  - id
  - title
```

Then generated source file `Task.ts` has a compilation error `TS2532: Object is possibly undefined`. The TypeScript version is 5.3.3 (latest).

![image](https://github.com/OpenAPITools/openapi-generator/assets/10975834/e1327364-fbb2-47d5-9bc4-647bf8eb6774)

##### openapi-generator version

At the current latest commit of the master branch (a8efb8e)

##### Related issues/PRs

This bug seems to have been introduced by #17798.

##### Suggest a fix

Typescript compiler does not understand the function `exists()` ensures the value is present. `exists()` simply assert the value is not null or undefined, so a quick fix will be using `==` operator like this.

```ts
        'dueDate': value['dueDate'] == null  ? undefined : ((value['dueDate']).toISOString().substring(0,10)),
```

**Comment by wing328** [comment]
FYI @noordawod  - the author of https://github.com/OpenAPITools/openapi-generator/pull/17798

**Comment by airxnoor** [comment]
Thanks for the fix, I'll double check on my end too.

**Comment by topce** [comment]
Nice work @kota65535
Small remark
expression in 
```
'dueDate': value['dueDate'] == null  ? undefined : ((value['dueDate']).toISOString().substring(0,10)), 
```
could be written in typescript  
```
'dueDate': value.dueDate?.toISOString().substring(0,10)),
```
or 
```
'dueDate': value['dueDate']?.toISOString().substring(0,10)),
```
so called optional chaining 
could be future improvement
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
