### ISSUE TITLE
[BUG][JAVA] cannot find symbol JSON

### ISSUE THREAD

**Issue by brunobottazzini** [OpenAPITools/openapi-generator#14270]
#### Bug Report Checklist

- [Y] Have you provided a full/minimal spec to reproduce the issue?
- [Y] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [Y] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [Y] Have you searched for related issues/PRs?
- [] What's the actual output vs expected output?: The object generated does not compile and it should.

##### Description

After upgrading lib we cannot generate anymore object see image below.
![image](https://user-images.githubusercontent.com/4460234/208085425-1e5e26a4-6430-4fe3-9502-7e818b843013.png)

##### openapi-generator version

After upgrading from version 5.4.0 to 6+ any version

##### Steps to reproduce

I have created a small project showing the problem: https://github.com/brunobottazzini/openapi-generator-json

Just run `mvn clean install`

![image](https://user-images.githubusercontent.com/4460234/208085683-9d6577ff-d65d-4ca5-8333-ed7455ae3bfa.png)

##### Related issues/PRs

I could not find any issues related. Somehow after upgrading the library the generator is creating method as fromJSON and toJSON, the problem is that JSON.getGSON() is not found. 

Maybe it was a problem in my dependencies or configuration of the plugin but, i could not find any configuration or dependency that could resolve the issue. So to make it to work we were forced to make a downgrade to version 5.4.0.

##### Suggest a fix
It could be option the generation of the methods fromJSON and toJSON.

**Comment by argenstijn** [comment]
Can you try:

 <generateSupportingFiles>true</generateSupportingFiles>

**Comment by brunobottazzini** [comment]
Hi @argenstijn, thank you for your response.

Enabling supporting files produces new errors for me. 

Inside file ApiClient.java from _target/generated-sources/swagger/com_

```
package okhttp3.internal.http does not exist
package okhttp3.internal.tls does not exist
package okhttp3.logging does not exist
package okhttp3.logging.HttpLoggingInterceptor does not exist
package okio does not exist
package okio does not exist
package okio does not exist
cannot find symbol
```

**Comment by Van-Romel** [comment]
Same issue here, I've updated the gson version as well. Same issue.

**Comment by argenstijn** [comment]
Sorry for my late response. 

package okhttp3.internal.http does not exist
package okhttp3.internal.tls does not exist
package okhttp3.logging does not exist
package okhttp3.logging.HttpLoggingInterceptor does not exist
package okio does not exist
package okio does not exist
package okio does not exist
cannot find symbol

Did you add all the necessary dependencies to your maven pom like 


<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>okhttp</artifactId>
    <version>3.14.9</version>
</dependency>


<dependency>
    <groupId>com.squareup.okio</groupId>
    <artifactId>okio</artifactId>
    <version>3.3.0</version>
</dependency>

<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>logging-interceptor</artifactId>
    <version>3.14.9</version>
</dependency>

**Comment by juniormbe** [comment]
Hi @brunobottazzini, I did something simple that worked for me.
Try following these steps, it could definitely work for you too :

- At the root of your project (same level as the `pom.xml`), add the `.openapi-generator-ignore` file
- In the file, add a line to skip the generation of the JSON.java file: `src/main/java/<path-to-generation-base-package>/JSON.java` (egg. `src/main/java/com/test/myapp/apiclient/JSON.java`)

Try to clean and compile again.

**Comment by aliberti91** [comment]
Hi Bruno, after several tests and searches, together with @aserricchio, we found this solution:

- Add the following properties at configuration level: 

```
<generateSupportingFiles>true</generateSupportingFiles>
<supportingFilesToGenerate>
JSON.java
</supportingFilesToGenerate>
``` 

- Add the following dependencie in pom (I'm using 1.8.5 version):
```
<dependency>
    <groupId>io.gsonfire</groupId>
    <artifactId>gson-fire</artifactId>
    <version>${gsonfire.version}</version>
</dependency>
``` 
Beware of the CVE-2022-25647 vulnerability

**Comment by fatlun1981** [comment]
In my case, adding library=webclient in configOptions works for me. I am using springboot in my project.
`							<configOptions>
								<library>webclient</library>
							</configOptions>`
As this will generate the client using webclient and jackson, the gson related issue is gone.
