### PR TITLE
[Spring] Remove @Nullable annotation for NativeWebRequest in Spring controller

### LINKED ISSUE #23581: [BUG] [Spring] Nullable annotation not imported in Spring-Boot controllers
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Compilation error for generated spring-boot generated rest controller.
`@Nullable` annotation is set for NativeWebRequest.  The annotation is not imported in all cases.  For example when the operations have only required arguments.

##### openapi-generator version

7.22.0-SNAPSHOT

##### Generation Details

java  -jar openapi-generator-cli.jar  generate -g spring --library spring-boot -i modules/openapi-generator/src/test/resources/3_0/petstore.yaml -o /tmp/output

##### Steps to reproduce

The generated `/tmp/output/src/main/java/org/openapitools/api/UserApiController.java`
contains a `@Nullable` annotation, but no import.

It gives a compilation error

##### Related issues/PRs

Regression due to #23256

##### Suggest a fix

Quick fix: remove the annotation from `apiController.mustache`
Mid term fix:
  
  correclty add `@Nullable` annotation in all the java and spring generators.  The goal is is to avoid false alarms when using JSpecify. Ensure that `@Nullable` annotations are correctly imported

### PR DESCRIPTION
**Pull request by jpfinne**
Avoid compilation error due to missing import for `@Nullable` annotation put in Spring controllers

Fixes #23581 (Regression coming from introduction of jspecify)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package || exit
  ./bin/generate-samples.sh ./bin/configs/*.yaml || exit
  ./bin/utils/export_docs_generators.sh || exit
  ``` 
  (For Windows users, please run the script in [WSL](https://learn.microsoft.com/en-us/windows/wsl/install))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR solves a reported issue, reference it using [GitHub's linking syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) (e.g., having `"fixes #123"` present in the PR description)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

---
## Summary by cubic
Removed `@Nullable` from `NativeWebRequest` in generated Spring controllers to avoid missing `org.springframework.lang.Nullable` imports with jspecify. Tests now ensure `@Nullable` is not applied to `NativeWebRequest` while `org.jspecify.annotations.Nullable` imports remain where expected.

- **Bug Fixes**
  - Removed `@Nullable` from the `NativeWebRequest` field and constructor param in `apiController.mustache`.

- **Refactors**
  - Strengthened tests with precise pattern matching (avoids `JsonNullable` false positives), new import assertions (`doesImportAnnotation`/`doesNotImportAnnotation` supporting short or FQCN), and clearer assertion messages; added checks that `org.jspecify.annotations.Nullable` is imported in generated files (including Spring Boot controllers) but not used on `NativeWebRequest`.

<sup>Written for commit 41a93412920980a349b61749a045f900f0461941. Summary will update on new commits.</sup>

### CODE REVIEW

**Comment by jpfinne** [comment]
@wing328  This fixes a compilation error.  It might be good to include in 7.22

**Comment by wing328** [comment]
thanks for the fix

please resolve the merge conflicts and i'll try to get it merged before upcoming release.

**Comment by jpfinne** [comment]
> thanks for the fix
> 
> please resolve the merge conflicts and i'll try to get it merged before upcoming release.

@wing328 done

**Comment by wing328** [comment]
cc @cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02) @Zomzog (2022/09) @martin-mfg (2023/08)
