### ISSUE TITLE
[BUG][Swift5] Generator output not compilable with uniqueItems

### ISSUE THREAD

**Issue by pgrosslicht** [OpenAPITools/openapi-generator#7281]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

#6773 introduced a change where `Set` is used instead of Arrays when the array spec has the uniqueItems flag set. `Set` however needs all elements to conform to `Hashable`, which they do not. 

##### openapi-generator version
v5.0.0-beta a77fd44
was working in v4.3.1 003165c

##### OpenAPI declaration file content or url

https://gist.github.com/pgrosslicht/c519f7e011eee94ed356779a0096e256

##### Generation Details

swift5 generator with everything as default

##### Steps to reproduce

```sh
java -jar openapi-generator-cli-5.0.0-beta.jar generate -i error.yaml -g swift5
swift build
```
Build will fail with
```sh
OpenAPIClient/Classes/OpenAPIs/APIs/PetsAPI.swift:20:37: error: type 'Pet' does not conform to protocol 'Hashable'
    open class func createPets(pet: Set<Pet>, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
```

##### Related issues/PRs

Introduced in #6773 

##### Suggest a fix

1) Make all structs conform to `Hashable`. This should work since Swift can automatically synthesize the `Hashable` protocol in most cases, but might lead to some edge cases where Swift is not capable of synthesizing them.
2) Introduce config option for the change original change in #6773 and the suggested `Hashable` conformance.

**Comment by wing328** [comment]
@pgrosslicht thanks for filing the issue. I've filed https://github.com/OpenAPITools/openapi-generator/pull/7300 to fix it.
