### PR TITLE
[REQ-22001] Add MCP server support to apiService.mustache

### PR DESCRIPTION
**Pull request by thibautrety**
Refactor apiService.mustache to include MCP server support and enhance operation methods.

The goal is to directly generate a MCP server in quarkus. <br/>
Two extensions are used : 
- x-enable-mcp-server : (default is false) at the root of the spec, states that mcp server is enabled. It should be set to true in order to be enabled
- x-enable-mcp-operation : (default is false) On each operation that should be accessible from MCP clients. It states if an specific operation can be accessible from MCP client

The main intent is to transform our REST APIs as GEN-AI ready APIs. <br/>
**Known Limitations** <br/>
- UUID in parameters ar not supported yet
- SecurityContext parameters is not supported yet

**See also**<br/>
An example of usage can be found here : https://github.com/thibautrety/quarkus_mcp/tree/main

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package || exit
  ./bin/generate-samples.sh ./bin/configs/*.yaml || exit
  ./bin/utils/export_docs_generators.sh || exit
  ``` 
  (For Windows users, please run the script in [WSL](https://learn.microsoft.com/en-us/windows/wsl/install))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR solves a reported issue, reference it using [GitHub's linking syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) (e.g., having `"fixes #123"` present in the PR description)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR

please follow step 3 to update the samples so as to fix https://github.com/OpenAPITools/openapi-generator/actions/runs/18679590784/job/53712868648?pr=22197

**Comment by thibautrety** [comment]
Hello @wing328 , 
Thank you very much for your feedback.
I have updated samples. Please let me know if it is ok or if something remains to be modified

**Comment by wing328** [comment]
when you've time, can you please review the build failure?

**Comment by thibautrety** [comment]
> when you've time, can you please review the build failure?

Hello,
Yes of course. I'll do it as soon as possible. Thank you

**Comment by thibautrety** [comment]
Hello @wing328 , I have just submitted the fix. Thanks

**Comment by thibautrety** [comment]
Hello @wing328,
This is a kind reminder. Is there anything else to be done from my side ?
Thanks

**Comment by wing328** [comment]
thanks again for the contribution.

let's give it a try

**Comment by wing328** [comment]
can you please review the build failure after merging this change into master?

https://github.com/OpenAPITools/openapi-generator/actions/runs/20296806573/job/58292320011

https://github.com/OpenAPITools/openapi-generator/actions/runs/20296806573/job/58292320017

error message:
```
[INFO] Compiling 23 source files to /home/runner/work/openapi-generator/openapi-generator/samples/server/petstore/jaxrs-resteasy/default/target/classes
[INFO] -------------------------------------------------------------
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/openapi-generator/openapi-generator/samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/api/PetApiService.java:[164,19] cannot find symbol
  symbol:   variable additionalMetadata
  location: interface org.openapitools.api.PetApiService
Error:  /home/runner/work/openapi-generator/openapi-generator/samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/api/PetApiService.java:[164,38] cannot find symbol
  symbol:   variable _file
  location: interface org.openapitools.api.PetApiService
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
```

not sure why the jaxrs tests were skipped in the PR (maybe due to cloudflare outage)

if we cannot find a fix, we will need to revert the change via https://github.com/OpenAPITools/openapi-generator/pull/22551
