### PR TITLE
[#9805][Kotlin][multiplatform] Make the template work with Kotlin 1.5.x

### PR DESCRIPTION
**Pull request by krzema12**
### Issue
[[BUG][kotlin-client][multiplatform] "NoSuchMethodError" in runtime when starting ktor server with Kotlin 1.5.10 · Issue #9805 · OpenAPITools/openapi-generator](https://github.com/OpenAPITools/openapi-generator/issues/9805) (https://github.com/OpenAPITools/openapi-generator/issues/9805)

### Details

The goal of this change is to make Kotlin multiplatform template work with the newest Kotlin version (1.5.10).
Without these changes, consuming generated module from a Kotlin 1.5-based module with a Ktor server
results in a runtime exception when installing the JSON feature.

My guess is that due to some breaking changes kotlinx.serialization. For consistency, all kotlinx libraries were
updated, to adhere to the recommended versions mentioned here: https://kotlinlang.org/docs/releases.html#release-details

This change is meant to be as simple as possible - just bumping the versions and making minimal necessary adjustments.
I'm planning to introduce other changes (remove unneeded stuff, address warnings which will become errors in the future, add end-to-end tests if not present, and so on) in separate PR(s).

### Testing done

* ran integration tests (`mvn integration-test -f samples/client/petstore/kotlin-multiplatform`)
* created an entry point in the generated sample project and made a few test calls. I didn't test all APIs, it was rather meant to be a smoke test

### To be clarified
* are there any end-to-end tests that actually try to call the Petstore service with the generated module?
* how to ensure there are no regressions in other Kotlin templates that reuse the shared pieces of template?
* is `master` the right target branch for this change? The policy is confusing to me

I'd expect there are some tests ran by the CI that will address my above concerns. That's why I'm posting this PR anyway, to see what workflows GitHub will trigger, and to get feedback from the community.

### FYI

Kotlin technical committee: @jimschubert, @dr4ke616, @karismann, @Zomzog, @andrewemery, @4brunu, @yutaka0m

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by 4brunu** [comment]
I think this PR changes some things that will conflict with https://github.com/OpenAPITools/openapi-generator/pull/9755

**Comment by krzema12** [comment]
@4brunu thanks for referencing the PR! Indeed, my PR seems to be actually not needed once that one is merged. I'll engage in reviewing it.

**Comment by 4brunu** [comment]
Thanks, your review on the other PR will be helpful 👍

**Comment by krzema12** [comment]
Closing in favor of https://github.com/OpenAPITools/openapi-generator/pull/9755 which is more correct and comprehensive.
