### PR TITLE
[BUGFIX][Rust] Array with unique enum items no longer causes mismatched types error

### LINKED ISSUE #16849: [BUG][Rust] Array with unique enum items causes mismatched types error
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Components containing arrays of unique enum items are converted to models where the property is typed as a `std::collections::HashSet<T>` in the struct, but typed as a `Vec<T>` in the constructor arguments, resulting in `error[E0308]: mismatched types` during the build process.

###### Current output

```Rust
pub struct Foo {
    #[serde(rename = "bar")]
    pub bar: std::collections::HashSet<Bar>,
}

impl Foo {
    pub fn new(bar: Vec<Bar>) -> Foo {
        Foo {
            bar,
        }
    }
}
```

###### Expected output
Arguments should be typed as `std::collections::HashSet<T>` as well to match the generated struct.

```Rust
pub struct Foo {
    #[serde(rename = "bar")]
    pub bar: std::collections::HashSet<Bar>,
}

impl Foo {
    pub fn new(bar: std::collections::HashSet<Bar>) -> Foo {
        Foo {
            bar,
        }
    }
}
```

##### openapi-generator version

7.0.1

##### OpenAPI declaration file content or url

```yaml
# minimal_example.yaml

openapi: 3.0.3

info: 
  version: 1.0.0
  title: Unique Items Array

paths:
  /foo:
    get:
      description: Returns an array with unique items
      responses: 
        '200':
          description: Array with unique items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/foo'

components:
  schemas:
    foo:
      type: object
      required:
        - bar
      properties: 
        bar:
          type: array
          description: An array containing unique items
          uniqueItems: true
          example: 
            - 1
            - 2
            - 3
          items:
            type: integer
            enum:
              - 1
              - 2
              - 3
            example: 1
```

##### Generation Details

```yaml
generatorName: rust
outputDir: generated/rust
library: reqwest
inputSpec: minimal_example.yaml
templateDir: modules/openapi-generator/src/main/resources/rust
additionalProperties:
  supportAsync: false
  packageName: openapi
```

##### Steps to reproduce
```sh
openapi-generator-cli generate -g rust -i minimal_example.yaml -o generated/rust

cd generated/rust
cargo build
```

##### Related issues/PRs
Possibly introduced in https://github.com/OpenAPITools/openapi-generator/pull/8693

##### Suggest a fix
Template file for rust models, modules/openapi-generator/src/main/resources/rust/model.mustache, should be updated so not only struct vars are checked for `{{#uniqueItems}}`, but also arguments in `pub fn new`.

```
pub fn new({{#requiredVars}}{{{name}}}: {{#isNullable}}Option<{{/isNullable}}{{#isEnum}}{{{enumName}}}{{/isEnum}}{{^isEnum}}{{{dataType}}}{{/isEnum}}{{#isNullable}}>{{/isNullable}}{{^-last}}, {{/-last}}{{/requiredVars}}) ->
```
Should become

```
pub fn new({{#requiredVars}}{{{name}}}: {{#isNullable}}Option<{{/isNullable}}{{#isEnum}}{{#isArray}}{{#uniqueItems}}std::collections::HashSet<{{/uniqueItems}}{{^uniqueItems}}Vec<{{/uniqueItems}}{{/isArray}}{{{enumName}}}{{#isArray}}>{{/isArray}}{{/isEnum}}{{^isEnum}}{{{dataType}}}{{/isEnum}}{{#isNullable}}>{{/isNullable}}{{^-last}}, {{/-last}}{{/requiredVars}}) -> {{{classname}}} {
```

### PR DESCRIPTION
**Pull request by SAIA-Basseldonk**
## Summary
Components containing arrays of unique enum items were converted to models where the property is typed as a `std::collections::HashSet<T>` in the struct, but typed as a `Vec<T>` in the constructor arguments, resulting in `error[E0308]: mismatched types` during the build process.

Added check for `uniqueItems` in the arguments for `fn new` in `model.mustache`.

## Issue
fix #16849

## OpenAPI Example
```yaml
# minimal_example.yaml

openapi: 3.0.3

info: 
  version: 1.0.0
  title: Unique Items Array

paths:
  /foo:
    get:
      description: Returns an array with unique items
      responses: 
        '200':
          description: Array with unique items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/foo'

components:
  schemas:
    foo:
      type: object
      required:
        - bar
      properties: 
        bar:
          type: array
          description: An array containing unique items
          uniqueItems: true
          example: 
            - 1
            - 2
            - 3
          items:
            type: integer
            enum:
              - 1
              - 2
              - 3
            example: 1
```

## Command to generate client
```sh
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g rust -i minimal_example.yaml -o generated/rust

cd generated/rust
cargo build
```

Cargo build should now be successful.

## Technical committee
@frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05) @jacob-pro (2022/10)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
can you please add a test to `modules/openapi-generator/src/test/resources/3_0/rust/petstore.yaml` and regenerate the samples following step 3 in the PR checklist?
