### ISSUE TITLE
[JAVA][SPRING] Arrays are not rendered correctly in responses

### ISSUE THREAD

**Issue by superplan** [OpenAPITools/openapi-generator#14178]
##### Description

Objects of type "array" are not rendered correctly in responses, see example below. The UI shows only an item of the array, which is misleading.

##### openapi-generator version
6.2.1

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.3
info:
  version: 1.0.0
  title: See, thats an array!
  description: An example to demonstrate how array responses are rendered in Swagger-UI.
paths:
  /free-donuts:
    get:
      description: Process data
      operationId: getDonuts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Donut'
components:
  schemas:
    Donut:
      type: object
      required:
        - menuName
      properties:
        name:
          type: string
          description: key
        glazed:
          type: boolean
          description: value
```
##### Command line used for generation

`java -jar openapi-generator-cli-6.2.1.jar generate -g spring -i input.yaml -o "spring_6.2.1" -c config.yaml`

Here is my config.yaml:
```
additionalProperties:
  useTags: true
  java8: true
  useOptional: true
  useBeanValidation: true
  delegatePattern: true
```
Produces:
![image](https://user-images.githubusercontent.com/16057393/205628743-d173d9d3-c418-4f75-8c9f-c0bedacb7858.png)

Expect:
![image](https://user-images.githubusercontent.com/16057393/205628654-23324abc-3472-47d1-bfa8-0c93a8ef2c7f.png)

##### Steps to reproduce

Generate spring-Server und run as java application. Schema for the response code 200 is "Donut" and not an array of "Donut".

##### Suggest a fix/enhancement

Incorporate [@ArraySchema](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#arrayschema) into api.mustache. Here the fix is code enclosed by tag "{{#isArray}}":

```java
...
import io.swagger.v3.oas.annotations.media.ArraySchema;
...
        responses = {
            {{#responses}}
            @ApiResponse(responseCode = "{{{code}}}", description = "{{{message}}}"{{#baseType}}, content = {
                {{#produces}}
                @Content(mediaType = "{{{mediaType}}}", {{#isArray}}array = @ArraySchema( {{/isArray}}schema = @Schema(implementation = {{{baseType}}}.class)){{#isArray}}){{/isArray}}{{^-last}},{{/-last}}
                {{/produces}}
            }{{/baseType}}){{^-last}},{{/-last}}
            {{/responses}}
        }

```

Now the DefaultApi.java should look like this:
```java
...
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful response", content = @Content(
        		mediaType = "application/json", 
        		array = @ArraySchema(schema = @Schema(implementation = DonutBox.class))
        		))
        })
...
```

Instead of:
```java
...
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful response", content = @Content(
        		mediaType = "application/json", 
        		schema = @Schema(implementation = DonutBox.class)
        		))
        })
...
```

**Comment by Bsd15** [comment]
For me, in the generated API class the return type is set to `ResponseEntity<Object>` which is causing swagger to render empty response. 

```yaml
openapi: 3.1.0
info:
  title: Cats API
  version: 0.1.0
  summary: API for Cats
  description: Practice project for OpenAPI specification
paths:
  /cats:
    post:
      description: Add a new cat
      summary: Add a cat
      operationId: addCat
      requestBody:
        description: Request for creating a new cat
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Cat'
      responses:
        '201':
          description: Cat has been added successfully.
    get:
      description: Get all cats
      summary: Get Cats
      operationId: getCats
      responses:
        '200':
          description: Cats response
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cat'
components:
  schemas:
    Cat:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        status:
            type: string
            enum:
              - available
              - adopted
              - dead

```
**CatsAPI.java**
```java
    /**
     * GET /cats : Get Cats
     * Get all cats
     *
     * @return Cats response (status code 200)
     */
    @Operation(
        operationId = "getCats",
        summary = "Get Cats",
        responses = {
            @ApiResponse(responseCode = "200", description = "Cats response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/cats",
        produces = { "application/json" }
    )
    default ResponseEntity<Object> getCats(
        
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }
```

**POM.xml**
```xml
<plugin>
<groupId>org.openapitools</groupId>
<artifactId>openapi-generator-maven-plugin</artifactId>
<!-- RELEASE_VERSION -->
<version>6.2.1</version>
<!-- /RELEASE_VERSION -->
<executions>
	<execution>
		<goals>
			<goal>generate</goal>
		</goals>
		<configuration>
			<inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
			<generatorName>spring</generatorName>
			<configOptions>
				<sourceFolder>src/gen/java/main</sourceFolder>
				<interfaceOnly>true</interfaceOnly>
			</configOptions>
		</configuration>
	</execution>
</executions>
</plugin>
```

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/39040503/205859391-0a328e60-555f-44c8-97dd-2f46cffee25a.png">

**Comment by ataylormays-duetto** [comment]
My team is facing the same issue.

**Comment by borsch** [comment]
> For me, in the generated API class the return type is set to `ResponseEntity<Object>` which is causing swagger to render empty response.
> 
> ```yaml
> openapi: 3.1.0
> info:
>   title: Cats API
>   version: 0.1.0
>   summary: API for Cats
>   description: Practice project for OpenAPI specification
> paths:
>   /cats:
>     post:
>       description: Add a new cat
>       summary: Add a cat
>       operationId: addCat
>       requestBody:
>         description: Request for creating a new cat
>         content:
>           'application/json':
>             schema:
>               $ref: '#/components/schemas/Cat'
>       responses:
>         '201':
>           description: Cat has been added successfully.
>     get:
>       description: Get all cats
>       summary: Get Cats
>       operationId: getCats
>       responses:
>         '200':
>           description: Cats response
>           content:
>             'application/json':
>               schema:
>                 type: array
>                 items:
>                   $ref: '#/components/schemas/Cat'
> components:
>   schemas:
>     Cat:
>       type: object
>       required:
>         - id
>         - name
>       properties:
>         id:
>           type: integer
>         name:
>           type: string
>         description:
>           type: string
>         status:
>             type: string
>             enum:
>               - available
>               - adopted
>               - dead
> ```
> 
> **CatsAPI.java**
> 
> ```java
>     /**
>      * GET /cats : Get Cats
>      * Get all cats
>      *
>      * @return Cats response (status code 200)
>      */
>     @Operation(
>         operationId = "getCats",
>         summary = "Get Cats",
>         responses = {
>             @ApiResponse(responseCode = "200", description = "Cats response", content = {
>                 @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
>             })
>         }
>     )
>     @RequestMapping(
>         method = RequestMethod.GET,
>         value = "/cats",
>         produces = { "application/json" }
>     )
>     default ResponseEntity<Object> getCats(
>         
>     ) {
>         return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
> 
>     }
> ```
> 
> **POM.xml**
> 
> ```
> <plugin>
> <groupId>org.openapitools</groupId>
> <artifactId>openapi-generator-maven-plugin</artifactId>
> 
> <version>6.2.1</version>
> 
> <executions>
> 	<execution>
> 		<goals>
> 			<goal>generate</goal>
> 		</goals>
> 		<configuration>
> 			<inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
> 			<generatorName>spring</generatorName>
> 			<configOptions>
> 				<sourceFolder>src/gen/java/main</sourceFolder>
> 				<interfaceOnly>true</interfaceOnly>
> 			</configOptions>
> 		</configuration>
> 	</execution>
> </executions>
> </plugin>
> ```
> 
> <img alt="image" width="1443" src="https://user-images.githubusercontent.com/39040503/205859391-0a328e60-555f-44c8-97dd-2f46cffee25a.png">

change `openapi` version to '3.0.0' instead of '3.1.0'. seems like there are some changes on parser change which affect you. I'll create separate issue for this since this is global code update

**Comment by superplan** [comment]
When using `openapi` version '3.1.0' the tag `{{{baseType}}}` is returned as "Object". In my example (see Issue description) this generates:

`@Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))`

in the response method (DefaultApi.java), which is now a double bug. First you need:

`@Content(mediaType = "application/json", schema = @Schema(implementation = Donut.class))`

to avoid an empty response. Secondly, the final result should be

`@Content(mediaType = "application/json", array = @ArraySchema( schema = @Schema(implementation = Donut.class)))`

with regards to the array nature of the response object.

Just confirming that theses are two separate problems, as described in #14200. Thanks @borsch!

**Comment by borsch** [comment]
@superplan please try latest 6.3.0-SNAPSHOT

**Comment by superplan** [comment]
Using 6.3.0-SNAPSHOT (Build from Fri Jan 13 14:03:03 UTC 2023) it works with openapi versions `3.0.0`, `3.0.1`, `3.0.2` and `3.0.3`. Thanks @borsch!
For openapi version `3.1.0` an empty response is generated.

**Comment by borsch** [comment]
@superplan 3.1.0 is not unsupported as for now so it's a kind of expected result

**Comment by superplan** [comment]
That's fine with me. The issue can be closed now, since it will be resolved with generator version `6.3.0`.

**Comment by bjorgvino** [comment]
Has version `6.3.0` gotten a release date yet? I'm running into this issue using `6.2.1`. I tested `6.3.0-SNAPSHOT` and it does fix the array response issue, but I'm getting compilation errors in some generated models instead.

```cannot find symbol
symbol:   method requiredMode()
location: @interface io.swagger.v3.oas.annotations.media.Schema```

<img width="658" alt="image" src="https://user-images.githubusercontent.com/1465164/213650575-c8c8017a-b8e0-4376-804a-4c163d47cefb.png">

**Comment by bjorgvino** [comment]
The issue above is fixed by https://github.com/OpenAPITools/openapi-generator/pull/14496 (6.3.0 release).

**Comment by RisteJovanoski** [comment]
In version 6.6.0 the method `toUrlQueryString` is always generated, even though supportUrlQuery is not present or is disabled: `<configOptions><supportUrlQuery>false</supportUrlQuery></configOptions>`. Shouldn't this config option stop the generator from generating this method?
