### PR TITLE
[java][native] make generated APIs AutoCloseable and close the owned HttpClient

### LINKED ISSUE #24942: [BUG] [JAVA] `HttpClient memberVarHttpClient` not `close`d
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I noticed that the `XxxApi.java` file generated when using `library=native` calls `apiClient.getHttpClient()` and stores the resulting `HttpClient` in a `private` field, but never calls `.close()` on it. (This class was made `AutoCloseable` in Java 21, and [closing it is important](https://docs.oracle.com/en/java/javase/21/docs/api/java.net.http/java/net/http/HttpClient.html#close()) to release resources.) Clients of the library could not easily work around this; they would have to pass in a special `HttpClient.Builder` which tracked all the times `.build()` was called, and retain weak references so they could be closed later.

##### openapi-generator version

`openapi-generator-maven-plugin` version `7.25.0`

##### OpenAPI declaration file content or url

(see steps to reproduce)

##### Generation Details

(see steps to reproduce)

##### Steps to reproduce

```bash
git clone https://github.com/jenkinsci/cursor-origin-branch-source-plugin .
git checkout 2b2e1c5beaac428488aa5406e0d38721a572d57b
mvn -Pquick-build package
fgrep memberVarHttpClient target/generated-sources/openapi/io/jenkins/plugins/cursor_origin_branch_source/origin_openapi/api/OriginServiceApi.java
```

Expected: some call to `memberVarHttpClient.close()`. Actual: none, just created and then used to make requests.

**NOTE**: I tried to reproduce in trunk (f99cf3bbbbb9c5eee56f4298a667db0c326d40ee) but compilation failed for some apparently unrelated reason: missing `Enum.java`. (Bisected this to https://github.com/OpenAPITools/openapi-generator/pull/24812.) `OriginServiceApi.java` was still generated the same way, still compilable, still missing `.close()`.

##### Related issues/PRs

(none found)

##### Suggest a fix

Whatever template change would effect

```diff
116,116c116,116
< public class OriginServiceApi {
---
> public class OriginServiceApi implements AutoCloseable {
158a159,162
>   @Override
>   public void close() {
>      memberVarHttpClient.close();
>   }
```

when configured for Java 21+.

### PR DESCRIPTION
**Pull request by jtnord**
ApiClient.getHttpClient() returns builder.build(), so every native API instance is handed a freshly built HttpClient that no other instance shares. That client was never released, leaking its connection pool and threads for the lifetime of the process.

Generated API classes now implement AutoCloseable and close that client in close(), so they can be used in try-with-resources. HttpClient only became AutoCloseable in Java 21 while the native library targets Java 11, so the call is guarded by an instanceof check; on older runtimes there is no lifecycle API to call and close() is a no-op.

The other Java client libraries are intentionally left alone. They hold a shared ApiClient (usually the process-wide Configuration singleton) or wrap a client that is not closeable at all, so an API instance owns nothing it would be safe to close.

Note the current `master` does not build cleanly for me on windows either natively or in WSL, so several tests will only have been run in CI (tried with a variety of different JVMs, 25 fails with:

```
KotlinSpringServerCodegenTest.testXMinimumMessageAndXMaximumMessage_long -- Time elapsed: 0.437 s <<< ERROR!
java.lang.IllegalArgumentException: 25.0.4
```

11 fails with:

```
[main] WARN  io.swagger.v3.parser.OpenAPIV3Parser - Exception while reading:
io.swagger.v3.parser.exception.ReadContentException: Unable to read location `src/test/resources/3_0/petstore.yaml` 
```
followed by 
```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project openapi-generator: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test failed: org.junit.platform.commons.JUnitException: TestEngine with ID 'testng' failed to discover tests:
[ERROR] An error occurred while instantiating class org.openapitools.codegen.java.AbstractJavaCodegenTest: null: ExceptionInInitializerError: NullPointerException
```

fixes: #24942

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @martin-mfg  @KannaKim 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package || exit
  ./bin/generate-samples.sh ./bin/configs/*.yaml || exit
  ./bin/utils/export_docs_generators.sh || exit
  ``` 
  (For Windows users, please run the script in [WSL](https://learn.microsoft.com/en-us/windows/wsl/install))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR

please review the feedback from cubic-dev-ai when you've time
