### ISSUE TITLE
[BUG] V7.2.0 Breaks Schema Validation Imports

### ISSUE THREAD

**Issue by jnels124** [OpenAPITools/openapi-generator#17485]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Upgrading to version 7.2 produces errors when defining array parameters with pattern validation on the items

##### openapi-generator version

7.2

##### OpenAPI declaration file content or url
```
openapi: 3.0.3
paths:
  /api/v1/list:
    get:
      summary: List stuff
      description: |
        The description

      operationId: listStuff
      parameters:
        - $ref: "#/components/parameters/timestampQueryParam"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StuffResponse"
      tags:
        - stuff

tags:
  - name: stuff
    description: somestuff
info:
  title: Example
  version: 0.0.0-SNAPSHOT
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
  description: "description"

externalDocs:
  description: EXAMPLE
  url: "https://google.com"
components:
  schemas:
    StuffResponse:
      type: object
      properties:
        someProp:
          description: "This is a description"
          type: string
          example: "This is an example"
  parameters:
    timestampQueryParam:
      description: a timestamp param
      name: timestamp
      in: query
      explode: true
      schema:
        type: array
        items:
          type: string
          pattern: ^((eq|gt|gte|lt|lte|ne):)?\d{1,10}(.\d{1,9})?$
```

##### Steps to reproduce

1. Configure the above spec and run `openApiGenerate`

**Comment by jnels124** [comment]
The error produced with this spec is:
```
/StuffApi.java:91: error: cannot find symbol
  public StuffResponse listStuff(List<@Pattern(regexp = "^((eq|gt|gte|lt|lte|ne):)?\\d{1,10}(.\\d{1,9})?$")String> timestamp) throws ApiException {
                                       ^
  symbol:   class Pattern
  location: class StuffApi
/Users/jessenelson/IdeaProjects/hedera-mirror-node2/hedera-mirror-rest-java/build/generate-resources/main/com/hedera/mirror/rest/api/StuffApi.java:103: error: cannot find symbol
  public ApiResponse<StuffResponse> listStuffWithHttpInfo(List<@Pattern(regexp = "^((eq|gt|gte|lt|lte|ne):)?\\d{1,10}(.\\d{1,9})?$")String> timestamp) throws ApiException {
                                                                ^
  symbol:   class Pattern
  location: class StuffApi
/Users/jessenelson/IdeaProjects/hedera-mirror-node2/hedera-mirror-rest-java/build/generate-resources/main/com/hedera/mirror/rest/api/StuffApi.java:132: error: cannot find symbol
  private HttpRequest.Builder listStuffRequestBuilder(List<@Pattern(regexp = "^((eq|gt|gte|lt|lte|ne):)?\\d{1,10}(.\\d{1,9})?$")String> timestamp) throws ApiException {
                                                            ^
  symbol:   class Pattern
  location: class StuffApi
```

**Comment by steven-sheehy** [comment]
This is a regression caused by #17165 and a [comment](https://github.com/OpenAPITools/openapi-generator/pull/17165#issuecomment-1880910250) on that PR also notes the same.

**Comment by evialina** [comment]
Hi @wing328, @jimschubert , @cbornet , @jmini , @etherealjoy. This is still a problem using v7.7.0 for jaxrs-spec generator when schemaMappings or typeMappings are used.
