### ISSUE TITLE
[Java][jaxrs 2.1/resteasy] compilation error because of @PATCH 

### ISSUE THREAD

**Issue by tnmtechnologies** [OpenAPITools/openapi-generator#2018]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

By default, @PATCH annotation is resolved to package io.swagger.jaxrs.* .
PATCH annotation was not part of jaxrs 2.0 specifications ( [https://jax-rs.github.io/apidocs/2.1/](https://jax-rs.github.io/apidocs/2.0/) ) but it is now part of jaxrs 2.1 specifications ([https://jax-rs.github.io/apidocs/2.1/](https://jax-rs.github.io/apidocs/2.1/)).
 
Compilation with jaxrs 2.1 leads to a compilation failure because of imports with wild cards for both packages io.swagger.jaxrs.*  and javax.ws.rs.* . 

##### openapi-generator version

3.3.3

##### Steps to reproduce

The issue occurs when we upgrade our thorntail dependency from 2.2.0 (2.2.0) to 2.3.0 (jarxrs 2.1).

##### Suggest a fix

The suggested fix is to replace @PATCH in the generated source code by @io.swagger.jaxrs.PATCH.
By the way, the generated source will compile for any jaxrs version.

As a work around, we use the com.google.code.maven-replacer-plugin:replacer maven plugin in order to update the generated source code on the fly. Of course we have to apply it everywhere @PATCH is generated.

**Comment by jmini** [comment]
Thank you for opening this issue.

The JaxRS generator needs some love anyway... See #27.

In thorntail it would be much better to use [MicroProfile OpenAPI](https://github.com/eclipse/microprofile-open-api) but we do not have the generator for it yet.

---

I agree with your idea for the patch, having `@io.swagger.jaxrs.PATCH` fully qualified.

Can you send a Pull Request for that?

Let me know if you need help.

**Comment by tnmtechnologies** [comment]
Thanks.
I will do my best to send a PR asap.

**Comment by tnmtechnologies** [comment]
@jmini  @wing328  I have sent a Pull Request. Unfortunately the tests failed on CircleCI ([https://circleci.com/gh/OpenAPITools/openapi-generator/4576#tests/containers/2](https://circleci.com/gh/OpenAPITools/openapi-generator/4576#tests/containers/2)) .
The errors seem to be related to uncommited changes about php-ze-ph generator which is out of my changes.
How could we fix them?

**Comment by tnmtechnologies** [comment]
@jmini @wing328 CircleCI failure is fixed

**Comment by sachinpipal** [comment]
Also facing the same issue while generating code thorugh OpenAPI Plugin.

It says "@PATCH" is ambiguous, whicl results in compilation error.
Asking for implicitly import for io.swagger.ws.rs.PATCH  either javax.ws.rs.PATCH

**Comment by wutingbupt** [comment]
Hi,

The same problem for us.

Br,

Tim

**Comment by sachinpipal** [comment]
It is working fine with openapi 4.0.0 beta4 version .
Also with version with 3.3.4 +io swagger parser 2.0.Latset_version.

**Comment by wutingbupt** [comment]
Thanks for your info, beta4 haven't uploaded to the Maven central yet, I
will wait and test it.

Br,
Tim

sachinpipal <notifications@github.com> 于2019年5月9日周四 下午2:47写道：

> It is working fine with openapi 4.0.0 beta4 version .
> Also with version with 3.3.4 +io swagger parser 2.0.Latset_version.
>

**Comment by sachinpipal** [comment]
Sorry for the typoe its beta3 actually

**Comment by wutingbupt** [comment]
Beta3 contains another problem, something related to "duplicated
parameters" https://github.com/OpenAPITools/openapi-generator/issues/2631

sachinpipal <notifications@github.com> 于2019年5月10日周五 上午7:40写道：

> Sorry for the typoe its beta3 actually
>
