### PR TITLE
Resolve large int overflow, issue21805 

### LINKED ISSUE #21805: [BUG] [RUST Server] Invalid validation generated for large integers after updating to 7.15
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

After updating the generator to `7.15`, building our Rust Server fails to compile due to invalid validation rules being generated for large integers.

##### openapi-generator version

The generation works fine on both version however, after updating to 7.15, the generated code does not compile and fails with the following error:

```
error[E0600]: cannot apply unary operator `-` to type `u64`
   --> src/models.rs:887:34
    |
887 |             range(min = 0, max = -8446744073709551616),
    |                                  ^ cannot apply unary operator `-`
    |
    = note: unsigned values cannot be negated
```

##### OpenAPI declaration file content or url

```
openapi: 3.0.0

info:
  title: 'Example'
  description: 'test'
  version: 0.0.1
  contact:
    email: 'info@pietrobongiovanni.com'

servers:
  - url: '{protocol}://{hostname}:{port}/api/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      hostname:
        default: 'localhost'
      port:
        default: '8080'

components:

  schemas:
    paginationResponse:
      type: object
      properties:
        page:
          type: integer
          minimum: 0
          maximum: 10000000000000000000
          example: 0
        pageSize:
          type: integer
          minimum: 1
          maximum: 10000000000000000000
          example: 100
      required:
        - page
        - pageSize

    deviceId:
      type: string
      description: 'Device unique identifier'
      example: 'device_01jrd1sbzpfg89kqzcfazy6d0q'

    device:
      allOf:
        - type: object
          required:
            - id
          properties:
            id:
              $ref: '#/components/schemas/deviceId'

    paginatedDevices:
      type: object
      required:
        - items
        - pagination
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/device'
        pagination:
          $ref: '#/components/schemas/paginationResponse'

paths:
  /devices:
    summary: 'Devices'
    get:
      operationId: getDevices
      responses:
        '200':
          description: '(200) OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paginatedDevices'
```

##### Generation Details

We generate the code in a podman container. Generation works fine but the subsequent cargo build of the server fails. Please see this `generate.sh`:

```
#!/bin/bash

OPENAPI_GENERATOR_VERSION=v7.14.0

set -x

rm -rf generated/

podman run --rm -v "$(pwd)":/repo:Z openapitools/openapi-generator-cli:$OPENAPI_GENERATOR_VERSION \
    generate \
    -i /repo/openapi.yaml \
    -g rust-server \
    -o /repo/generated/rust-server \
    --model-name-prefix api \
    --additional-properties hideGenerationTimestamp=true

pushd "$(pwd)/generated/rust-server" > /dev/null
echo
echo "Building rust-server library..."
echo
cargo build
echo
echo "Building rust-server example client..."
echo
cargo build --example client
echo
echo "Building rust-server example server..."
echo
cargo build --example server
popd > /dev/null
```

##### Steps to reproduce

Copy the above openapi.yaml and generate.sh in a folder and run `generate.sh`  to generate and build the rust server.
With `OPENAPI_GENERATOR_VERSION=v7.14.0` the server will compile successfully.
If you set `OPENAPI_GENERATOR_VERSION` to `v7.15.0` the compilation of the server will fail:

```
error[E0600]: cannot apply unary operator `-` to type `u64`
   --> src/models.rs:461:34
    |
461 |             range(min = 1, max = -8446744073709551616),
    |                                  ^ cannot apply unary operator `-`
    |
    = note: unsigned values cannot be negated

For more information about this error, try `rustc --explain E0600`.
```

### PR DESCRIPTION
**Pull request by dsteeley**
fixes #21805 

rust-server compilation failed with large maximums. Resolved by handling minimum and maximum using BigInt instead of longValue.
Tested by updating and regenerating samples and validating that the updated example compiles. 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package || exit
  ./bin/generate-samples.sh ./bin/configs/*.yaml || exit
  ./bin/utils/export_docs_generators.sh || exit
  ``` 
  (For Windows users, please run the script in [WSL](https://learn.microsoft.com/en-us/windows/wsl/install))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR solves a reported issue, reference it using [GitHub's linking syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) (e.g., having `"fixes #123"` present in the PR description)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. cc @frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05) @jacob-pro (2022/10)

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the quick fix

**Comment by pgoodjohn** [comment]
thanks for the fix! :raised_hands:
