### ISSUE TITLE
Spring code generation for java 11

### ISSUE THREAD

**Issue by FirstWithThisName** [OpenAPITools/openapi-generator#5572]
##### Description
Hello, I want to use swagger for a the reimplementation of an old project.  
So it a basicly a new project from scratch.

I started to declare the first 2 method in swagger.yaml and tried out the code generator.  
Because it is a new project I have to use an up-to-date java version and I want to use spring.
I gnerated the code using `java -jar ~/Downloads/swagger-codegen-cli-2.4.12.jar generate -l spring -i ./swagger.yaml --additional-properties java8 --additional-properties useOptional`

My swagger file:
```yaml
swagger: "2.0"

info:
  version: 0.1.0
  title: myservice API
  description: API extracted from myservice

schemes:
  - http
host: localhost:8080
basePath: /myservice/

securityDefinitions:
  BasicAuth:
    type: basic

paths:
  /webresources/userService/nextFreeUsername:
    get:
      summary: Get a username for creation
      tags:
        - RestUserService
      security:
        - BasicAuth: []
      description: Returns a unique username
      parameters:
       - name: company
         in: query
         description: Company of the new user
         type: string
       - name: country
         in: query
         description: Short name country of the new user
         type: string
       - name: firstname
         in: query
         description: firstname of new user
         type: string
       - name: lastname
         in: query
         description: lastname of new user
         type: string
      responses:
        200:
          description: Result entity with the next free username
          schema:
            type: object
            properties:
              value:
                type: string
              code:
                type: integer
                
  /webresources/userService/createUser:
    post:
      summary: Create a new user
      tags:
        - RestUserService
      consumes: 
        - application/json
      security:
        - BasicAuth: []
      description: Create a new user
      parameters:
      - in: body
        name: userCreateRequest
        description: user create request
        required: true
        schema:
          $ref: '#/definitions/UserCreateRequest'
      responses:
        200:
          description: A userCreateResult object
          schema:
            $ref: '#/definitions/UserCreateResult'
            
            
definitions:
  UserCreateResult:
    properties:
      initialPassword:
        type: string
      sAMAccountName:
        type: string
      upn:
        type: string
      email:
        type: string
        
  UserCreateRequest:
    properties:
      Title:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      Country:
        type: string
      Company:
        type: string
      Department:
        type: string
      EMailAddress:
        type: string
      Street:
        type: string
      Postcode:
        type: string
      City:
        type: string
      EmploymentTypeValuePrefix:
        type: string
      PhoneNumber:
        type: string
      CellphoneNumber:
        type: string
      Manager:
        type: string
      IssueKey:
       type: string
      ContainerPath:
       type: string
      Reporter:
       type: string
      ExpiryDate:
       type: string
      Mailbox:
        type: boolean
      Corporation:
       type: string
```

It is not possible to compile the code after the generation.  
`mvn install`

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project swagger-spring: Compilation failure: Compilation failure: 
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/ApiResponseMessage.java:[3,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/ApiResponseMessage.java:[7,27] package javax.xml.bind.annotation does not exist
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/ApiResponseMessage.java:[46,6] cannot find symbol
[ERROR]   symbol:   class XmlTransient
[ERROR]   location: class io.swagger.api.ApiResponseMessage
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[42,12] cannot find symbol
[ERROR]   symbol:   method getObjectMapper()
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[42,45] cannot find symbol
[ERROR]   symbol:   method getAcceptHeader()
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[43,17] cannot find symbol
[ERROR]   symbol:   method getAcceptHeader()
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[45,243] cannot find symbol
[ERROR]   symbol:   variable HttpStatus
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[45,49] cannot find symbol
[ERROR]   symbol:   method getObjectMapper()
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[46,26] cannot find symbol
[ERROR]   symbol:   class IOException
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[47,21] cannot find symbol
[ERROR]   symbol:   variable log
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[48,49] cannot find symbol
[ERROR]   symbol:   variable HttpStatus
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[52,13] cannot find symbol
[ERROR]   symbol:   variable log
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[54,37] cannot find symbol
[ERROR]   symbol:   variable HttpStatus
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[66,12] cannot find symbol
[ERROR]   symbol:   method getObjectMapper()
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[66,45] cannot find symbol
[ERROR]   symbol:   method getAcceptHeader()
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[67,17] cannot find symbol
[ERROR]   symbol:   method getAcceptHeader()
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[69,153] cannot find symbol
[ERROR]   symbol:   variable HttpStatus
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[69,49] cannot find symbol
[ERROR]   symbol:   method getObjectMapper()
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[70,26] cannot find symbol
[ERROR]   symbol:   class IOException
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[71,21] cannot find symbol
[ERROR]   symbol:   variable log
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[72,49] cannot find symbol
[ERROR]   symbol:   variable HttpStatus
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[76,13] cannot find symbol
[ERROR]   symbol:   variable log
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] /home/user/NetBeansProjects/myservice-rest/src/main/java/io/swagger/api/WebresourcesApi.java:[78,37] cannot find symbol
[ERROR]   symbol:   variable HttpStatus
[ERROR]   location: interface io.swagger.api.WebresourcesApi
[ERROR] -> [Help 1]
```

I can't  imagine that I am the only one with this problem.

**Comment by egemenvardar** [comment]
I also encountered the same problem after updating swagger-codegen to 2.4.13. I was using 2.4.10 before, and I didn't have this problem with that version.

**Comment by wing328** [comment]
> java -jar ~/Downloads/swagger-codegen-cli-2.4.12.jar generate -l spring -i ./swagger.yaml --additional-properties java8 --additional-properties useOptional

This project is not the same as https://github.com/swagger-api/swagger-codegen.

Please consider migrating the to latest version of OpenAPI Generator to see if you still experience the same issue: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/migration-from-swagger-codegen.md

**Comment by wing328** [comment]
> --additional-properties java8 --additional-properties useOptional

That's the issue. Please use `--additional-properties useOptional=true,java8=true` instead in OpenAPI Generator CLI
