### ISSUE TITLE
[C++-Qt] qHash: invalid initialization of reference in autogenerated code

### ISSUE THREAD

**Issue by pbielefeldt** [OpenAPITools/openapi-generator#17739]
##### Description

When generating code using the `cpp-qt-client` for Qt5 in version 6 or 7, compiling will lead to errors of type

```sh
[ 11%] Building CXX object CMakeFiles/QtOpenAPIClient.dir/OAIOrder.cpp.o
In file included from /cpp/client/OAIOrder_dimensions.h:25:0,
                 from /cpp/client/OAIOrder.h:23,
                 from /cpp/client/OAIOrder.cpp:12:
/cpp/client/OAIObject.h: In function 'uint OpenAPI::qHash(const OpenAPI::OAIObject&, uint)':
/cpp/client/OAIObject.h:72:34: error: invalid initialization of reference of type 'const OpenAPI::OAIObject&' from expression of type 'QJsonObject'
     return qHash(obj.asJsonObject(), seed);
                  ~~~~~~~~~~~~~~~~^~
/cpp/client/OAIObject.h:71:1: note: in passing argument 1 of 'uint OpenAPI::qHash(const OpenAPI::OAIObject&, uint)'
 qHash(const OAIObject& obj, uint seed = 0) noexcept{
 ^~~~~
make[2]: *** [CMakeFiles/QtOpenAPIClient.dir/build.make:76: CMakeFiles/QtOpenAPIClient.dir/OAIOrder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/QtOpenAPIClient.dir/all] Error 2
```

##### openapi-generator version

I have experienced this with the openapi-generator-cli available in the `openapitools/openapi-generator-cli:v6.6.0` and `v7.2.0` images.
With `v5.4.0` I got other errors preventing me from compiling.
I can confirm that `v4.3.1` works with my configuration and setup.

I compile on openSUSE Leap 15.5 using CMake, and I a pretty sure I have all the required packages available.

##### OpenAPI declaration file content or url

I follow the steps described in the Qt example found at
https://www.qt.io/resources/videos/qt-and-openapi-swagger-a-tutorial-dev-des-2021, or
https://blog.basyskom.com/2021/qml-qt-quick-and-swagger-openapi-tutorial.

The specification file is:
https://github.com/basysKom/swagger_qt_demo/blob/182e70418779e07998d48a99ff7247f23ae7d183/swagger.yaml

##### Command line used for generation

To generate, I use 
```bash
docker run --rm -v ${PWD}:/local/ openapitools/openapi-generator-cli:v7.2.0 generate -i /local/swagger.yaml -g cpp-qt-client -o /local/generated/cpp/
```

##### Steps to reproduce

- Download the file from the demo (see above)
- Generate the Qt code
- Build a docker image based on openSUSE Leap 15.5, with make, cmake, and all the required Qt devel packages (most likely, the error also occurs with a different setup)
- run the image with the generated code mounted
  ```bash
  docker run -ti -v ${PWD}/generated/cpp/:/cpp/ my-docker-image:15.5 /usr/bin/env bash
  ```
- create a build directory
  ```bash
  mkdir $HOME/apibuild/
  cd $HOME/apibuild/
  ```
- generate the C++ code, specify the Qt version (not sure how I am supposed to set `$QT_VERSION_MAJOR` else)
  ```bash
  cmake -DQT_VERSION_MAJOR=5 /cpp/client/
  ```
- try compiling
  ```bash
  make
  ```

My expectation is that this would create a library in C++ that I can use in my project. And it does that for version 4.3.1, but not 6 or 7. 

This might have to do with how the generator handles `QT_VERSION`.  Also, Qt5 (which I use), and Qt6 differ in the return type  of `qHash`: `uint` [in Qt5](https://doc.qt.io/qt-5/qhash.html#qHash-4x), and `size_t` [in Qt6](https://doc.qt.io/qt-6.5/qhash.html#qHash-4x).

##### Related issues/PRs

My suspicion is that this has to do with #11621, but I can't prove that.
