### ISSUE TITLE
[BUG] Jackson dependency required when okhttp-gson is choosen

### ISSUE THREAD

**Issue by efren1villamagua** [OpenAPITools/openapi-generator#18515]
The generated code for java with `okhttp-json` has a problem.

For some in-house reason we can't use Jackson libraries.
Until version 7.2.0 the file **`JSON.java`** is generated with a Google dependency (`com.google.gson.internal.bind.util.ISO8601Utils`) but from 7.3.0 version a Jackson dependency is used (`com.fasterxml.jackson.databind.util.StdDateFormat`) what causes a compilation error.

Dependency used in my project is: **`org.openapitools:openapi-generator-gradle-plugin:7.5.0`**

Configuration is:
```
openApiGenerate {
    generatorName = "java"
    library = "okhttp-gson"
    inputSpec = "...".toString()
    outputDir = "...".toString()
    apiPackage = "..."
    invokerPackage = "..."
    modelPackage = "..."
    configOptions = [
            dateLibrary                             : "java8",
            disallowAdditionalPropertiesIfNotPresent: "false",
            enumUnknownDefaultCase                  : "true",
            useOneOfDiscriminatorLookup             : "true"
    ]
    globalProperties = [
            skipFormModel: "false",
            apiTests     : "false",
            modelTests   : "false"
    ]
    skipValidateSpec = true
    logToStderr = true
    generateAliasAsModel = false
    enablePostProcessFile = false
    cleanupOutput = true
}
```

**Comment by Philzen** [comment]
@winrid seems also affected by this. My expectation would also be that any gson client should not have any jackson dependency whatsoever, be it direct or transitive.

That change was introduced in 76560e34c9aacd9d7593ac45bd204e2edf38abd9 via #17052. @ChaosMarc @martin-mfg i followed your discussion over there, so i'm trying to make the best of both worlds possible over via #18811 – i'm welcoming your comments.

Though GSON is in maintenance mode, the implementation in question has recently been committed to: https://github.com/Marcono1234/gson/blob/main/gson/src/main/java/com/google/gson/internal/bind/util/ISO8601Utils.java – so IMHO for GSON fanfolks this import should still be fine.
