### PR TITLE
Remove deprecated methods in default codegen

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

A follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/859.

### CODE REVIEW

**Comment by ackintosh** [comment]
https://app.shippable.com/github/OpenAPITools/openapi-generator/runs/2928/1/console
> [ERROR] COMPILATION ERROR : 
> [ERROR] /root/src/github.com/OpenAPITools/openapi-generator/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartJaguarClientCodegen.java:[147,38] cannot find symbol
>   symbol:   method underscore(java.lang.String)
>   location: class org.openapitools.codegen.languages.DartJaguarClientCodegen

Oh, shippable has failed. 👀

**Comment by jmini** [comment]
From a Java-API point of view (for people having their own generator) this is a breaking change without fallback.

I suggest to target 4.0 for a change like this one.

cc: @jimschubert

**Comment by wing328** [comment]
@jmini agreed with you. The user using a customized generator will need to do something in order to make it work after upgrading to 3.3.0 if we decide to merge the PR into master.

I don't mind targeting this change for 4.0.x instead.

**Comment by wing328** [comment]
@ackintosh I think that's because shippable merged origin/master into this branch. I'll merge master or 4.0.x into this branch later after we have a decision on which branch to target.
