### PR TITLE
[typescript-fetch] Fix TS2590 in instanceOf guards for wide sanitized-name models (#23980)

### LINKED ISSUE #23980: [BUG][typescript-fetch] instanceOf type guards produce "TS2590: union type too complex" for models with many sanitized (snake_case) required properties
Bug Report Checklist
- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator?
- [x] Have you tested with the latest master to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?

Description

As of 7.23.0, the typescript-fetch generator emits instanceOf<Model> type guards that fail to compile with error TS2590: Expression produces a union type that is too complex to represent when a model has many required properties whose name differs from baseName (e.g. snake_case JSON keys camelCased into the TS interface).

This is a regression introduced by #23497, which added a dual-key check guarded by hasSanitizedName in modelGeneric.mustache:

{{#hasSanitizedName}}
if ((!('{{name}}' in value) && !('{{baseName}}' in value)) || (value['{{name}}'] === undefined && value['{{baseName}}'] === undefined)) return false;
{{/hasSanitizedName}}

Because the function is a type predicate (value is {{classname}}) and each clause performs two indexed-access reads (value['camelCase'], value['snake_case']) against a parameter typed object, TypeScript computes a narrowed candidate union after every clause. For a model where most/all required fields are sanitized (any snake_case API), the union width grows past the compiler's internal limit and trips TS2590. Skinny models stay under the threshold; wide models (≈15+ sanitized required props) fail.

APIs that serialize snake_case are hit on nearly every model, since name !== baseName for essentially every field.

openapi-generator version

7.23.0 (regression introduced in this version; 7.22.0 and earlier generate compilable guards). Latest release at time of filing.

OpenAPI declaration / minimal spec
```
openapi: 3.0.3
info:
  title: repro
  version: 1.0.0
paths:
  /thing:
    get:
      operationId: getThing
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Thing'
components:
  schemas:
    Thing:
      type: object
      properties:
        aws_region:        { type: string }
        aws_account_name:  { type: string }
        aws_account_number:{ type: string }
        created_at:        { type: string }
        updated_at:        { type: string }
        # ...repeat enough snake_case required props to cross the union limit (~15+)
      required:
        - aws_region
        - aws_account_name
        - aws_account_number
        - created_at
        - updated_at
```
Generation command
```
openapi-generator-cli generate -i repro.yaml -g typescript-fetch -o ./out
cd out && tsc --noEmit
```
Generated output (abbreviated)
```
export function instanceOfThing(value: object): value is Thing {
    if ((!('awsRegion' in value) && !('aws_region' in value)) || (value['awsRegion'] === undefined && value['aws_region'] === undefined)) return false;
    // ...one per required field...
    return true;
}
```
tsc reports TS2590 on the value['...'] === undefined reads.

Steps to reproduce
1. Generate the spec above with typescript-fetch on 7.23.0.
2. Run tsc --noEmit against the output.
3. Observe TS2590 on the instanceOf guard.

Suggested fix

A few directions (maintainers' call):
- Widen the parameter type or read through (value as any) for the indexed-access checks so TS doesn't narrow the predicate on each clause; or
- Keep the discriminator-value fix from #23497 but drop the dual name/baseName membership narrowing in favor of checking only baseName (the raw-JSON key) — which was the actual bug #23497 targeted; or
- Split the single boolean chain into sequential statements that don't accumulate one large union.

Related issues/PRs

Regression from #23497 (merged in 7.23.0).

### PR DESCRIPTION
**Pull request by seonwooj0810**
Fixes #23980

### Problem

As of 7.23.0 the `typescript-fetch` generator emits `instanceOf<Model>` type guards that fail to compile with **TS2590: "Expression produces a union type that is too complex to represent"** when a model has many required properties whose sanitized TS name differs from the JSON `baseName` (e.g. any snake_case API).

The dual `name`/`baseName` membership check added in #23497 reads through the `value` parameter (typed `object`) on every clause:

```ts
if ((!('awsRegion' in value) && !('aws_region' in value)) || (value['awsRegion'] === undefined && value['aws_region'] === undefined)) return false;
```

Because the function is a type predicate (`value is Model`), each `in`/index-access against `value` narrows the parameter, and the candidate union grows on every clause. With ~15+ sanitized required fields the union crosses the compiler's internal limit and trips TS2590. Skinny models stay under the threshold, which is why it was not caught by existing samples.

### Fix

Read the membership and index-access checks in the `hasSanitizedName` branch through `value as Record<string, any>` so TypeScript no longer narrows the predicate on each clause. This keeps the dual-key (name + baseName) behavior introduced by #23497 while restoring compilable guards. The non-sanitized branch (single-key) is unchanged — it never accumulated the cross-product union and already compiles for wide models.

Only `modelGeneric.mustache` changed; the regenerated samples are a mechanical consequence.

### Verification

- **Reproduced** the failure: a model with 18 required snake_case properties generated on `master` produces a guard that fails `tsc --noEmit` with TS2590.
- **After the fix**, the same spec generates a guard that compiles cleanly (`tsc --noEmit --strict`, exit 0).
- Regenerated all `typescript-fetch` samples (`./bin/generate-samples.sh ./bin/configs/typescript-fetch-*.yaml`) — 9 model files updated; the changed `snakecase-discriminator` build's models type-check cleanly under `--strict`.

Verification done: 1 (no in-flight PR — `gh pr list`/code-search), 2 (no claims on the issue), 3 (fix is in the `.mustache` template + generated `.ts`), 4 (grepped the dual-key pattern on master, confirmed present), end-to-end repro before/after with `tsc`.

---
## Summary by cubic
Fixes TS2590 (“union type too complex”) in `typescript-fetch` when generating `instanceOf<Model>` guards for models with many required fields whose TS names differ from their JSON `baseName`. Guards now compile while preserving dual-key checks.

- **Bug Fixes**
  - Cast `value` to `Record<string, any>` for dual `name`/`baseName` membership and discriminator checks to stop type predicate narrowing.
  - Retains behavior from #23497; single-key path unchanged.
  - Updated `modelGeneric.mustache`; regenerated affected samples; updated `TypeScriptFetchClientCodegenTest` assertions to expect the casts.

<sup>Written for commit 3b1d30a8ac68c4502a4cc262ab4a053ef2e71c81. Summary will update on new commits.</sup>

<a href="https://cubic.dev/pr/OpenAPITools/openapi-generator/pull/23982?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR

cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04) @joscha (2024/10) @dennisameling (2026/02)

**Review by macjohnny — APPROVED** [review]
thanks for the fix
