### PR TITLE
[Java] Fix #24875: Add missing import for direct enum property reference in parameters

### LINKED ISSUE #24875: [BUG][JAVA] Direct property enum reference used by parameter omits generated model import
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The Java client generator produces uncompilable code when a query parameter schema directly references an inline enum property of a component schema.

The generator promotes the inline enum to a model enum (`StockState`), but the generated API class uses that type without importing it.

**Actual result**

The generator creates:

```text
src/main/java/org/openapitools/client/model/StockState.java
```

but generates `DefaultApi.java` with unqualified uses of `StockState`:

```java
public okhttp3.Call listArchivesCall(
    @javax.annotation.Nullable StockState state,
    final ApiCallback _callback) throws ApiException {
```

`DefaultApi.java` does not contain:

```java
import org.openapitools.client.model.StockState;
```

Compilation fails five times with:

```text
error: cannot find symbol
  symbol:   class StockState
  location: class DefaultApi
```

**Expected result**

The generated Java client should compile. `DefaultApi.java` should import `StockState`, or use its fully qualified name.

##### openapi-generator version

`7.26.0-SNAPSHOT`, built from current master commit `b391b2b98c5926ee9842ef3bc863b57c4d824bbe`.

Also happens in `7.24.0`.

This has not been bisected to identify the first affected version.

##### OpenAPI declaration file content or url

```yaml
openapi: 3.1.0
info:
  title: Enum parameter import
  version: 1.0.0
paths:
  /archives:
    get:
      operationId: listArchives
      parameters:
        - name: state
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/Archive/properties/state"
      responses:
        "200":
          description: Success
components:
  schemas:
    Archive:
      type: object
      properties:
        state:
          type: string
          enum:
            - ACTIVE
```

##### Generation Details

```sh
java -jar openapi-generator-cli.jar generate \
  -g java \
  -i enum-not-imported.yaml \
  -o generated \
  --skip-validate-spec \
  --additional-properties modelNamePrefix=Stock,hideGenerationTimestamp=true
```

##### Steps to reproduce

1. Save the OpenAPI declaration above as `enum-not-imported.yaml`.
2. Validate it:

   ```sh
   java -jar openapi-generator-cli.jar validate -i enum-not-imported.yaml
   ```

3. Generate the Java client with the command above.
4. Compile the generated client:

   ```sh
   cd generated
   mvn -q -DskipTests compile
   ```

##### Related issues/PRs

- did not find any

##### Suggest a fix

`DefaultCodegen#fromParameter` handles imports specially for array parameter items, but the direct scalar enum reference in this reproducer is not added to the API operation's import set.

When a parameter's resolved schema produces a generated enum model type, add that type to the operation imports so the Java API template emits:

```java
import org.openapitools.client.model.StockState;
```

### PR DESCRIPTION
**Pull request by Harshavardhan2951**
### PR Title
[Java] Fix #24875: Add missing import for direct enum property reference in parameters

### Description of the change
Fixes #24875

When a query parameter references a direct enum property via
`$ref: "#/components/schemas/Component/properties/field"`, the required
import statement was missing from the generated API class, causing
compilation failures.

This fix updates `DefaultCodegen#fromParameter` to add the resolved enum
type to the operation's import set, with a guard against composed/generic
types (containing `&` or `<`) that are not valid single-type imports.

### PR Checklist
- [x] Read the contribution guidelines.
- [x] Pull Request title conforms to conventions.
- [x] Ran `mvn clean install` to ensure all unit tests pass.
- [x] Added unit test in `DefaultCodegenTest.java` verifying enum imports
      are included when a parameter directly references an enum property.
- [ ] Generated updated samples using `./bin/generate-samples.sh`.

---
## Summary by cubic
Fixes generated code missing enum imports when a query parameter directly references an enum property via `$ref` (issue #24875). Previously the generated API class failed to compile because the resolved enum type wasn't imported; now `fromParameter` adds it to the operation's imports, skipping composed/generic type strings containing `&` or `<`.

Side effect: regenerated JavaScript samples now include `import [String] from '../model/[String]'` lines, which are invalid JavaScript imports and may break the `javascript-apollo`, `javascript-es6`, and `javascript-promise-es6` generators.

<sup>Written for commit 3ba2cb1311abfc2b7524390f78108f9efda28fe7. Summary will update on new commits.</sup>

<a href="https://cubic.dev/pr/OpenAPITools/openapi-generator/pull/24918?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

**Comment by Harshavardhan2951** [comment]
The JavaScript CI failure is a pre-existing issue on master, 
unrelated to this Java fix. The same 6 JS files change when 
running `./bin/generate-samples.sh` on master branch as well.

**Comment by Harshavardhan2951** [comment]
@cubic review

**Comment by wing328** [comment]
thanks for the PR

cc @OpenAPITools/generator-core-team
