### ISSUE TITLE
[BUG][JAVA] Compilation error when using useSealedOneOfInterfaces with serializableModel

### ISSUE THREAD

**Issue by rafaljaw** [OpenAPITools/openapi-generator#23308]
##### Description

Openapigenerator 7.20.0 produces code that is not compiling when mixing serializableModel=true and useSealedOneOfInterfaces=true and having oneOf object in openapi spec. The reason it is not compiling is duplicated final keyword in generated class:
```java
public final final class HelloADto implements Serializable, HelloResponseDto {
```

##### openapi-generator version

7.20.0

##### OpenAPI declaration file content or url

```xml
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>7.20.0</version>
    <executions>
        <execution>
            <configuration>
                <configOptions>
                    <library>webclient</library>
                    <useJakartaEe>true</useJakartaEe>
                    <serializationLibrary>jackson</serializationLibrary>
                    <serializableModel>true</serializableModel>
                    <useOneOfInterfaces>true</useOneOfInterfaces>
                    <useSealedOneOfInterfaces>true</useSealedOneOfInterfaces>
                </configOptions>
                <generatorName>java</generatorName>
                <inputSpec>${project.basedir}/src/main/resources/Test.yaml</inputSpec>
                <generateApis>false</generateApis>
                <generateModelTests>false</generateModelTests>
                <generateSupportingFiles>false</generateSupportingFiles>
                <modelNameSuffix>Dto</modelNameSuffix>
                <modelPackage>com.test</modelPackage>
            </configuration>
            <goals>
                <goal>generate</goal>
            </goals>
            <id>test-api</id>
        </execution>
    </executions>
</plugin>
```

##### Generation Details

mvn clean package

##### Steps to reproduce

Generate dtos for the openapi config from above and the following sample openapi spec that causes compilation error:
[<script src="https://gist.github.com/rafaljaw/d8fc792dee7ba9ac0b8a3d909eaf9c12.js"></script>](https://gist.github.com/rafaljaw/d8fc792dee7ba9ac0b8a3d909eaf9c12)

**Comment by rafaljaw** [comment]
Just checked again with version 7.21.0 and it seems to work correctly now, so can be closed. It does not work with version 7.20.0 though which was the latest when I was creating the issue.
