### ISSUE TITLE
[BUG][JAVA] JDK 17 doesn't work with jaxrs-spec. Missing class javax.annotation.Generated.

### ISSUE THREAD

**Issue by jsyrjala** [OpenAPITools/openapi-generator#11795]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generating code with jaxrs-spec generates pom.xml that doesn't work with JDK17 and Maven 3.8.4. It is missing class `javax.annotation.Generated`.

```
mvn package

....

[INFO] Compiling 10 source files to /xxx/build/generated-oas-jaxrs-spec/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /xxx/build/generated-oas-jaxrs-spec/src/gen/java/com/xxx/model/Translation.java:[15,18] cannot find symbol
  symbol:   class Generated
  location: package javax.annotation
...

[INFO] 7 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.294 s
[INFO] Finished at: 2022-03-04T13:43:28+02:00
[INFO] ------------------------------------------------------------------------
...
```
Java version
```
% java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```
Maven version
```
% mvn --version
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /usr/local/Cellar/maven/3.8.4/libexec
Java version: 17.0.2, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/17.0.2/libexec/openjdk.jdk/Contents/Home
Default locale: en_FI, platform encoding: UTF-8
OS name: "mac os x", version: "12.2.1", arch: "x86_64", family: "mac"
```
##### openapi-generator version

5.4.0. Same thing happens with 5.3.1, after you enable compiler to generate JDK 1.8 code.

##### Suggest a fix

Include this in generated pom.xml
```xml
    <dependency>
      <groupId>javax.annotation</groupId>
      <artifactId>javax.annotation-api</artifactId>
      <version>1.3.2</version>
    </dependency>
```

**Comment by jsyrjala** [comment]
I guess the relevant bits of code are here: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaJaxRS/pom.mustache#L180-L188
```
{{#useBeanValidation}}
    <!-- Bean Validation API support -->
    <dependency>
        <groupId>jakarta.validation</groupId>
        <artifactId>jakarta.validation-api</artifactId>
        <version>${beanvalidation-version}</version>
        <scope>provided</scope>
    </dependency>
{{/useBeanValidation}}
```

I could make a PR to add `javax.annotation-api`, but not sure if it the right thing to do, and if it should replace or be in addition to `jakarta.validation-api` and if it should be inside or outside of `{{#useBeanValidation}}`.

**Comment by wing328** [comment]
Please kindly open a PR. 

I think it should be outside of `{{#useBeanValidation}}`
