### PR TITLE
[java][okhttp] Fixes #9151: Bump OkHTTP dependency to latest

### LINKED ISSUE #9151: [BUG][Java] ApiClient.java: error: no suitable method found for create(byte[],MediaType)
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Using the java generator against a basic spec, the generated project fails to compile.

##### openapi-generator version
5.1.0 and latest master (docker image 3c6b0382cd49)

Regression from 5.0.1

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Api

paths:
  /version:
    get:
      tags:
      - version
      summary: Gets the system version check
      operationId: getVersion
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionGetResponse'

components:
  schemas:
    VersionGetResponse:
      type: string
      description: The version of this service
      required:
        - status
      properties:
        status:
          type: string
          description: OK

```

##### Generation Details

`java -jar openapi-generator-cli-5.1.0.jar generate -g java -i service.yaml`

##### Steps to reproduce

1. Run the generator as described above
2. Try to compile the code with `./gradlew compileJava` or similar

###### Expected:
It will compile

###### Actual:
A bunch of:
```
out\java\src\main\java\org\openapitools\client\ApiClient.java:818: error: no suitable method found for create(byte[],MediaType)
            return RequestBody.create((byte[]) obj, MediaType.parse(contentType));
                              ^
    method RequestBody.create(MediaType,String) is not applicable
      (argument mismatch; byte[] cannot be converted to MediaType)
    method RequestBody.create(MediaType,ByteString) is not applicable
      (argument mismatch; byte[] cannot be converted to MediaType)
    method RequestBody.create(MediaType,byte[]) is not applicable
      (argument mismatch; byte[] cannot be converted to MediaType)
    method RequestBody.create(MediaType,File) is not applicable
      (argument mismatch; byte[] cannot be converted to MediaType)
```

### PR DESCRIPTION
**Pull request by toby-murray-snow-software**
In 5.0.1 the generated line in `ApiClient` was:
```
return RequestBody.create(MediaType.parse(contentType), (byte[]) obj);
```
in 5.1.0 it is:
```
return RequestBody.create((byte[]) obj, MediaType.parse(contentType));
```

Looks like this change was introduced in #8969, and requires a more recent version of OkHttp to compile in some (all?) circumstances.

I tested out the failing spec that was mentioned in the linked ticket, and it compiles now.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala  (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)  @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch  (2021/01)

### CODE REVIEW

File: modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache [hunk 1]
```diff
@@ -104,8 +104,8 @@ if(hasProperty('target') && target == 'android') {
 dependencies {
     implementation 'io.swagger:swagger-annotations:1.5.24'
     implementation "com.google.code.findbugs:jsr305:3.0.2"
-    implementation 'com.squareup.okhttp3:okhttp:3.14.7'
-    implementation 'com.squareup.okhttp3:logging-interceptor:3.14.7'
+    implementation 'com.squareup.okhttp3:okhttp:4.9.1'
+    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.1'
```
Comment (wing328) [inline modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache:108]: As part of this PR, can you please also update `build.sbt.mustache` by replacing `3.14.7` with `4.9.1` ?

Comment (wing328) [reply modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache:108]: Ignore it. I will file another PR instead.

**Comment by wing328** [comment]
Tested locally and the result is good.
