### ISSUE TITLE
[BUG][typescript-axios] The generated ts file from 5.0.0 cannot be transpiled.

### ISSUE THREAD

**Issue by jjtang1985** [OpenAPITools/openapi-generator#8542]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The generation works fine with the `5.0.0-beta2`. When switching to the stable version `5.0.0`, the generated code has some compilation errors: `TS2339: Property 'isJsonMime' does not exist on type 'Configuration'.`

##### openapi-generator version

5.0.0

##### OpenAPI declaration file content or url

```yaml
---
openapi: 3.0.0
info:
  title: Swagger Test Service
  description: Test Service for OpenApi version 2 aka. Swagger as YAML file.
  version: 1.0.0
paths:
  "/entities/{pathParam}":
    parameters:
    - in: path
      name: pathParam
      required: true
      schema:
        type: string
    post:
      summary: Test POST
      operationId: postEntity
      description: Test POST
      parameters:
      - in: query
        name: queryParam
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                items:
                  "$ref": "#/components/schemas/TestEntity"
      tags:
      - default
    patch:
      summary: Test PATCH
      operationId: patchEntity
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TestEntity"
      responses:
        '200':
          description: Success
      tags:
      - default
components:
  schemas:
    TestEntity:
      type: object
      properties:
        stringProperty:
          type: string
          description: A string property
        integerProperty:
          type: integer
          description: An integer property
tags:
- name: default
```

##### Generation Details

`npx openapi-generator-cli generate --input-spec /input-dir/open-api.json --generator-name typescript-axios --output /output-dir/openapi --template-dir /template-dir/templates --api-package api --model-package model --additional-properties withSeparateModelsAndApi=true --skip-validate-spec`

##### Steps to reproduce

1. Generate the client by using the command and the spec file above.
2. Transpile the generated code and see `TS2339: Property 'isJsonMime' does not exist on type 'Configuration'.`

##### Suggest a fix

Make `isJsonMime` as an optional function of the type `Configuration`.

**Comment by wing328** [comment]
> The generation works fine with the 5.0.0-beta2. When switching to the stable version 5.0.0, the generated code has some compilation errors:

@jjtang1985 thanks for reporting the issue. Do you mind doing a `git bisect` to figure out which commit may have broken it?

**Comment by macjohnny** [comment]
probably related to https://github.com/OpenAPITools/openapi-generator/pull/7892

**Comment by macjohnny** [comment]
the generated `Configuration` class implements the `isJsonMime` method:
https://github.com/OpenAPITools/openapi-generator/blob/5b82ed940762846689f95d9b2cd1f541385c58fd/modules/openapi-generator/src/main/resources/typescript-axios/configuration.mustache#L86-L89

so you need to create an instance of this `Configuration` class.

Does that resolve your issue?

**Comment by jjtang1985** [comment]
Hi @macjohnny , I resolve the issue by updating the configuration template from the `5.0.0`.
Thank you for taking care.

**Comment by denodaeus** [comment]
This works, but honestly, it makes for a really not-nice API:

Before:  
```typescript
const API = new TradeblottersApi({
        // TODO: for some reason swagger client removes port from requests if you don't specify the "basePath"
        basePath: 'http://localhost:3000',
        baseOptions: {
            withCredentials: true,
        },
    });
```
Now:

```typescript
const API = new TradeblottersApi(
    new Configuration({
        // TODO: for some reason swagger client removes port from requests if you don't specify the "basePath"
        basePath: 'http://localhost:3000',
        baseOptions: {
            withCredentials: true,
        },
    }),
);
```
