### ISSUE TITLE
[BUG] [Java] `Authentication undefined: my-auth-name` in ApiClient.java

### ISSUE THREAD

**Issue by Felk** [OpenAPITools/openapi-generator#19168]
### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] ~Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?~ I omitted this since the suspected pieces of code have not changed for a while, including recently.
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description and Reproduction

Given an OpenAPI with a security schema of type `openIdConnect`, e.g.:
```json
{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "My API",
    "version" : "1.0.0"
  },
  "security" : [ {
    "Keycloak" : [ ]
  } ],
  "paths" : {
    "/api/stuff" : {
      "post" : {
        "summary" : "Does something important.",
        "responses" : {
          "200" : {
            "description" : "Everything went well"
          }
        },
        "security" : [ {
          "Keycloak" : [ "api_access" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "Keycloak" : {
        "type" : "openIdConnect",
        "description" : "This service is secured through OIDC, implemented by Keycloak",
        "openIdConnectUrl" : "https://auth.example.com/realms/myrealm/.well-known/openid-configuration"
      }
    }
  }
}
```
and a generated Java client, e.g. through the openapi-generator maven plugin in a spring boot project:
```xml
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>7.7.0</version>
    <executions>
        <execution>
            <id>generate-my-client</id>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.build.directory}/my-openapi.json</inputSpec>
                <generatorName>java</generatorName>
                <library>webclient</library>
                <invokerPackage>com.example.myclient.invoker</invokerPackage>
                <apiPackage>com.example.myclient.api</apiPackage>
                <modelPackage>com.example.myclient.model</modelPackage>

                <configOptions>
                    <openApiNullable>false</openApiNullable>
                    <sourceFolder>myapi</sourceFolder>
                    <useSpringBoot3>true</useSpringBoot3>
                    <useJakartaEe>true</useJakartaEe>
                </configOptions>
            </configuration>
        </execution>
    </executions>
</plugin>
```
invocation fails with the following error:
```
org.springframework.web.client.RestClientException: Authentication undefined: Keycloak
	at com.example.myclient.invoker.ApiClient.updateParamsForAuth(ApiClient.java:701)
	at com.example.myclient.invoker.ApiClient.prepareRequest(ApiClient.java:622)
	at com.example.myclient.invoker.ApiClient.invokeAPI(ApiClient.java:582)
	at com.example.myclient.api.MergedApi.searchMarktrollenRequestCreation(MergedApi.java:8023)
	at com.example.myclient.api.MergedApi.searchMarktrollen(MergedApi.java:8039)
	at com.example.MyService.doClientCall(MyService.java:XY)
	[...]
```

which is emitted from this generated code:
```java
protected void updateParamsForAuth(String[] authNames, MultiValueMap<String, String> queryParams, HttpHeaders headerParams, MultiValueMap<String, String> cookieParams) {
    for (String authName : authNames) {
        Authentication auth = authentications.get(authName);
        if (auth == null) {
            throw new RestClientException("Authentication undefined: " + authName);
        }
        auth.applyToParams(queryParams, headerParams, cookieParams);
    }
}
```

##### openapi-generator version and Related issues/PRs

I tested 6.6.0, 7.5.0 and 7.7.0.
It worked with 6.5.0 and is "broken" since the initial OIDC support landed in 6.6.0: https://github.com/OpenAPITools/openapi-generator/pull/15417

##### Investigation and suggested fix

Previous to the initial OIDC support, source generation would just output the following error:

```
[ERROR] Unknown type `openIdConnect` found in the security definition `null`.
```

This also caused [`localVarAuthNames in api/MyApi.java`](https://github.com/OpenAPITools/openapi-generator/blob/v7.7.0/modules/openapi-generator/src/main/resources/Java/libraries/webclient/api.mustache#L134) to generate as follows:

```java
String[] localVarAuthNames = new String[] {  };
```

Starting with 6.6.0, the above error is no longer emitted during generation, and instead this code is emitted:

```java
String[] localVarAuthNames = new String[] { "Keycloak" };
```

In another generated file, the `invoker/ApiClient.java`, the init method is generated as follows for all versions I tested:
```java
protected void init() {
    // Setup authentications (key: authentication name, value: authentication).
    authentications = new HashMap<String, Authentication>();
    // Prevent the authentications from being modified.
    authentications = Collections.unmodifiableMap(authentications);
}
```

The respective mustache file [`ApiClient.mustache`](https://github.com/OpenAPITools/openapi-generator/blob/v7.7.0/modules/openapi-generator/src/main/resources/Java/ApiClient.mustache#L131C5-L131C57) currently looks like this:
```mustache
// Setup authentications (key: authentication name, value: authentication).
authentications = new HashMap<String, Authentication>();{{#authMethods}}{{#isBasic}}{{#isBasicBasic}}
authentications.put("{{name}}", new HttpBasicAuth());{{/isBasicBasic}}{{#isBasicBearer}}
authentications.put("{{name}}", new HttpBearerAuth("{{scheme}}"));{{/isBasicBearer}}{{/isBasic}}{{#isApiKey}}
authentications.put("{{name}}", new ApiKeyAuth({{#isKeyInHeader}}"header"{{/isKeyInHeader}}{{^isKeyInHeader}}"query"{{/isKeyInHeader}}, "{{keyParamName}}"));{{/isApiKey}}{{#isOAuth}}
authentications.put("{{name}}", new OAuth());{{/isOAuth}}{{/authMethods}}
// Prevent the authentications from being modified.
authentications = Collections.unmodifiableMap(authentications);
```

I believe there is a case for `isOpenIdConnect` missing in this template. I don't know how easily it could be added, or whether there needs to be some fallback mechanism for authentication mechanisms that are not supported by some code generators.

**Comment by Felk** [comment]
As a workaround in the meantime: Does anyone know how I could disable authentication altogether? The OpenAPI I'm consuming does have OIDC, but it's handled on a different layer so I don't actually need openapi-generator's support for it right now. The only workaround I found so far was downgrading to 6.5

**Comment by wing328** [comment]
@Felk what about removing security/auth setting in the spec as a workaround?

**Comment by Felk** [comment]
@wing328 that's a good suggestion. Unfortunately it doesn't quite work for us since we're currently downloading and processing the OpenAPI in a build step and therefore don't have a chance to manually modify it in-between. We also can't remove the authentication from the source since other consumers of the OpenAPI spec rely on the authentication to be there.

**Comment by MaurizioCasciano** [comment]
Same error for me with this OIDC security schema:

```yaml
  securitySchemes:
    OIDC-Auth:
      bearerFormat: jwt
      flows:
        authorizationCode:
          authorizationUrl: https://sso.project-io.eu/realms/REALM/protocol/openid-connect/auth
          scopes:
            email: email
            openid: openid
            profile: profile
          tokenUrl: https://sso.project-io.eu/realms/REALM/protocol/openid-connect/token
      in: header
      name: OIDC-Auth
      openIdConnectUrl: https://sso.project-io.eu/realms/REALM/.well-known/openid-configuration
      scheme: bearer
      type: openIdConnect
```

and this security section:

```yaml
security:
- OIDC-Auth: []
```

Can I do something on the Java consumer side to bypass this error until this issue gets fixed ?

**Comment by fischermatte** [comment]
We are facing the same, thanks for your analysis. So it looks like the open id connect is not supported yet?

**Comment by palatam** [comment]
[20648](https://github.com/OpenAPITools/openapi-generator/issues/20648)

**Comment by UnleashSpirit** [comment]
Hello, we're also experiencing this issue.
We're using two different OpenAPIs with two different security schemes.
To simplify the web client configuration, we generate the support files in the same "invokerPackage".
So, depending on the generation order in the pom.xml file, we're missing one authentication or another.

Perhaps it would be a good idea to add an option to the generator to disable authentication entirely? (Security is handled by another component.)
Or remove "Collections.unmodifiableMap", but I'm assuming it was added for a specific reason?

PS: Removing the "security" node is the workaroung we are using but we are not owner of the OpenAPI file so every update will break it.

**Comment by weimerb-tng** [comment]
Security scheme `openIdConnect` is not supported by the generator, see https://openapi-generator.tech/docs/generators/java/#security-feature
Better switch to another scheme.
